package net.frozenblock.wilderwild.mixin.worldgen;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import net.frozenblock.wilderwild.world.structure.WilderStructureProcessors;
import net.minecraft.data.worldgen.AncientCityStructurePools;
import net.minecraft.data.worldgen.Pools;
import net.minecraft.data.worldgen.placement.CavePlacements;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.levelgen.structure.pools.StructurePoolElement;
import net.minecraft.world.level.levelgen.structure.pools.StructureTemplatePool;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(AncientCityStructurePools.class)
public class AncientCityStructurePoolsMixin {

    @Inject(method = "<clinit>", at = @At("HEAD"), cancellable = true)
    public void name(CallbackInfo info) {
        info.cancel();
        Pools.register(new StructureTemplatePool(new ResourceLocation("ancient_city/structures"), new ResourceLocation("empty"), ImmutableList.of(Pair.of(StructurePoolElement.empty(), 7), Pair.of(StructurePoolElement.single("ancient_city/structures/barracks", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 4), Pair.of(StructurePoolElement.single("ancient_city/structures/chamber_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 4), Pair.of(StructurePoolElement.single("ancient_city/structures/chamber_2", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 4), Pair.of(StructurePoolElement.single("ancient_city/structures/chamber_3", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 4), Pair.of(StructurePoolElement.single("ancient_city/structures/sauna_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 4), Pair.of(StructurePoolElement.single("ancient_city/structures/small_statue", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 4), Pair.of(StructurePoolElement.single("ancient_city/structures/large_ruin_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/tall_ruin_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/tall_ruin_2", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/tall_ruin_3", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 2), Pair.of(StructurePoolElement.single("ancient_city/structures/tall_ruin_4", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 2), new Pair[]{Pair.of(StructurePoolElement.list(ImmutableList.of(StructurePoolElement.single("ancient_city/structures/camp_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), StructurePoolElement.single("ancient_city/structures/camp_2", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), StructurePoolElement.single("ancient_city/structures/camp_3", WilderStructureProcessors.CHEST_TO_STONE_GENERIC))), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/medium_ruin_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/medium_ruin_2", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/small_ruin_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/small_ruin_2", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/large_pillar_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/structures/medium_pillar_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.list(ImmutableList.of(StructurePoolElement.single("ancient_city/structures/ice_box_1"))), 1)}), StructureTemplatePool.Projection.RIGID));
        Pools.register(new StructureTemplatePool(new ResourceLocation("ancient_city/sculk"), new ResourceLocation("empty"), ImmutableList.of(Pair.of(StructurePoolElement.feature(CavePlacements.SCULK_PATCH_ANCIENT_CITY), 6), Pair.of(StructurePoolElement.empty(), 1)), StructureTemplatePool.Projection.RIGID));
        Pools.register(new StructureTemplatePool(new ResourceLocation("ancient_city/walls"), new ResourceLocation("empty"), ImmutableList.of(Pair.of(StructurePoolElement.single("ancient_city/walls/intact_corner_wall_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_intersection_wall_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_lshape_wall_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_2", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_2", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_3", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_4", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 4), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_passage_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 3), Pair.of(StructurePoolElement.single("ancient_city/walls/ruined_corner_wall_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/ruined_corner_wall_2", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), new Pair[]{Pair.of(StructurePoolElement.single("ancient_city/walls/ruined_horizontal_wall_stairs_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 2), Pair.of(StructurePoolElement.single("ancient_city/walls/ruined_horizontal_wall_stairs_2", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 2), Pair.of(StructurePoolElement.single("ancient_city/walls/ruined_horizontal_wall_stairs_3", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 3), Pair.of(StructurePoolElement.single("ancient_city/walls/ruined_horizontal_wall_stairs_4", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 3)}), StructureTemplatePool.Projection.RIGID));
        Pools.register(new StructureTemplatePool(new ResourceLocation("ancient_city/walls/no_corners"), new ResourceLocation("empty"), ImmutableList.of(Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_2", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_1", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_2", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_3", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_4", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_stairs_5", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1), Pair.of(StructurePoolElement.single("ancient_city/walls/intact_horizontal_wall_bridge", WilderStructureProcessors.CHEST_TO_STONE_WALLS), 1)), StructureTemplatePool.Projection.RIGID));
        Pools.register(new StructureTemplatePool(new ResourceLocation("ancient_city/city_center/walls"), new ResourceLocation("empty"), ImmutableList.of(Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/bottom_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/bottom_2", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/bottom_left_corner", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/bottom_right_corner_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/bottom_right_corner_2", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/left", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/right", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/top", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/top_right_corner", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city_center/walls/top_left_corner", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1)), StructureTemplatePool.Projection.RIGID));
        Pools.register(new StructureTemplatePool(new ResourceLocation("ancient_city/city/entrance"), new ResourceLocation("empty"), ImmutableList.of(Pair.of(StructurePoolElement.single("ancient_city/city/entrance/entrance_connector",WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city/entrance/entrance_path_1", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city/entrance/entrance_path_2", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city/entrance/entrance_path_3", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city/entrance/entrance_path_4", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1), Pair.of(StructurePoolElement.single("ancient_city/city/entrance/entrance_path_5", WilderStructureProcessors.CHEST_TO_STONE_GENERIC), 1)), StructureTemplatePool.Projection.RIGID));
    }
}