modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
    iconFile="assets/wilderwild/icon.png"
    authors="Lunade/AViewFromTheTop, Ethan Stokes, Soro"
    description='''
Overhauls the Wild Update, adding new features and improving existing ones.
    '''

[[mixins]]
config="wilderwild.mixins.json"

[[mixins]]
config="wilderwild.neoforge.mixins.json"

[[ dependencies.wilderwild ]]
    modId="neoforge"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.wilderwild ]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.wilderwild ]]
    modId="frozenlib"
    type="required"
    versionRange="[${frozenlib_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.wilderwild ]]
    modId="cloth-config"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

["lithium:options"]
"mixin.world.raycast" = false
