package net.frozenblock.wilderwild.mixin.client.warden;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.frozenblock.wilderwild.misc.WilderSharedConstants;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraft.client.animation.definitions.WardenAnimation;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Mutable;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Environment(EnvType.CLIENT)
@Mixin(value = WardenAnimation.class, priority = 999)
public class WardenAnimationOverwrites {

	@Final
    @Mutable
    @Shadow
	public static AnimationDefinition WARDEN_EMERGE;

    @Final
    @Mutable
    @Shadow
	public static AnimationDefinition WARDEN_SNIFF;

	@Shadow
	@Final
	@Mutable
	public static AnimationDefinition WARDEN_DIG;

	@Inject(method = "<clinit>", at = @At("TAIL"))
	private static void wilderWild$config(CallbackInfo info) {
		//TODO: config option for improved & dig
		WARDEN_DIG = AnimationDefinition.Builder.withLength(5.167667f)
				.addAnimation("body",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -16.48454f, -6.5784f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.posVec(0f, -16.48454f, -6.5784f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.0417f, KeyframeAnimations.posVec(0f, -16.97f, -7.11f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.625f, KeyframeAnimations.posVec(0f, -13.97f, -7.11f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.2083f, KeyframeAnimations.posVec(0f, -11.48454f, -0.5784f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.5417f, KeyframeAnimations.posVec(0f, -16.48454f, -6.5784f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.6667f, KeyframeAnimations.posVec(0f, -20.27f, -5.42f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.375f, KeyframeAnimations.posVec(0f, -21.48454f, -5.5784f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.0417f, KeyframeAnimations.posVec(0f, -22.48454f, -5.5784f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -40f, -8f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.posVec(0f, -51f, -18f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("body",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.25f, KeyframeAnimations.degreeVec(4.13441f, 0.94736f, 1.2694f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.degreeVec(50f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.degreeVec(54.45407f, -13.53935f, -18.14183f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.0417f, KeyframeAnimations.degreeVec(39.46442000000045f, -10.8885f, 35.7954f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.3333f, KeyframeAnimations.degreeVec(52.282610000000005f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.625f, KeyframeAnimations.degreeVec(53.23606f, 10.04715f, -29.72932f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.2083f, KeyframeAnimations.degreeVec(-17.71739f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.5417f, KeyframeAnimations.degreeVec(112.28261f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.6667f, KeyframeAnimations.degreeVec(116.06889f, 5.11581f, -24.50117f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.8333f, KeyframeAnimations.degreeVec(121.56244f, -4.17248f, 19.57737f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.0417f, KeyframeAnimations.degreeVec(138.56889f, 5.11581f, -24.50117f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.25f, KeyframeAnimations.degreeVec(144.06244f, -4.17248f, 19.57737f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.375f, KeyframeAnimations.degreeVec(147.28261f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.625f, KeyframeAnimations.degreeVec(147.28261f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.875f, KeyframeAnimations.degreeVec(134.36221f, 8.81113f, -8.90172f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.0417f, KeyframeAnimations.degreeVec(132.05966f, -8.35927f, 9.70506f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.25f, KeyframeAnimations.degreeVec(134.36221f, 8.81113f, -8.90172f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.5f, KeyframeAnimations.degreeVec(147.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.degreeVec(97.5f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("head",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2083433f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.7083435f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.0834335f, KeyframeAnimations.posVec(0f, 0f, -2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.3433335f, KeyframeAnimations.posVec(0f, 1f, -4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.8343335f, KeyframeAnimations.posVec(0f, 1f, -2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.041677f, KeyframeAnimations.posVec(0f, 1f, -2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.541677f, KeyframeAnimations.posVec(0f, 1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("head",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.6667f, KeyframeAnimations.degreeVec(13.086194851950495f, 17.072279894057374f, 3.9039914156746818f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2083f, KeyframeAnimations.degreeVec(14.143781649092034f, -13.465422583043619f, -8.330210660839839f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.75f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.375f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.5416765f, KeyframeAnimations.degreeVec(67.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.875f, KeyframeAnimations.degreeVec(11.600989497644605f, 15.69916503242257f, -1.7431514355125728f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-15.899010502355395f, -15.69916503242257f, 1.7431514355125728f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(-43.399010502355395f, 15.69916503242257f, -1.7431514355125728f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5416765f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.8343335f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.041677f, KeyframeAnimations.degreeVec(-58.91612381394225f, -9.995427666612159f, 28.83329384672652f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.25f, KeyframeAnimations.degreeVec(-58.91612381394225f, 9.995427666612159f, -28.83329384672652f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("right_arm",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.posVec(2.22f, 0f, 0.86f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1f, KeyframeAnimations.posVec(3.12f, 0f, 4.29f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.1676667f, KeyframeAnimations.posVec(2.97f, 0f, 4.44f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2916767f, KeyframeAnimations.posVec(2.81f, 9f, 4.41f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.3433333f, KeyframeAnimations.posVec(2.76f, 8.95f, 8.4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.4583433f, KeyframeAnimations.posVec(3.12f, 0f, 4.29f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.625f, KeyframeAnimations.posVec(2.79f, 4.4f, 7.96f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.75f, KeyframeAnimations.posVec(3.12f, 0f, 4.29f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.2083f, KeyframeAnimations.posVec(1f, 0f, 4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.5416765f, KeyframeAnimations.posVec(-1f, 0f, 4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.9167665f, KeyframeAnimations.posVec(0f, -5f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.0834335f, KeyframeAnimations.posVec(1f, 0f, 4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.2916765f, KeyframeAnimations.posVec(1f, -5f, 2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5f, KeyframeAnimations.posVec(1f, -5f, 2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.75f, KeyframeAnimations.posVec(1f, -10f, 2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.041677f, KeyframeAnimations.posVec(1f, -6f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.208343f, KeyframeAnimations.posVec(5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.375f, KeyframeAnimations.posVec(1f, -6f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.541677f, KeyframeAnimations.posVec(5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.posVec(0f, -5f, 2f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("right_arm",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.degreeVec(-101.8036f, -21.29587f, 30.61478f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.degreeVec(-101.8036f, -21.29587f, 30.61478f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1f, KeyframeAnimations.degreeVec(48.7585f, -17.61941f, 9.9865f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.1667f, KeyframeAnimations.degreeVec(48.7585f, -17.61941f, 9.9865f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.4583f, KeyframeAnimations.degreeVec(-116.44114910879516f, 19.3433334118835f, 10.863704906542015f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.75f, KeyframeAnimations.degreeVec(-89.04994f, -4.19657f, -1.47845f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.2083f, KeyframeAnimations.degreeVec(-158.30728f, 3.7152f, -1.52352f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.5416765f, KeyframeAnimations.degreeVec(-87.07754f, -0.02625f, 3.132f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.9167665f, KeyframeAnimations.degreeVec(-156.29763744742513f, -35.82603738046282f, -5.757830407450911f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-90f, 17.5f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(-168.20592954115864f, -20.448262127520593f, 14.45370892182791f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5f, KeyframeAnimations.degreeVec(-89.99999913388092f, 10.00000003724108f, -17.499999849600044f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.75f, KeyframeAnimations.degreeVec(-182.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.041677f, KeyframeAnimations.degreeVec(-185f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.208343f, KeyframeAnimations.degreeVec(-179.99999999999955f, 20f, -89.99999999999955f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.375f, KeyframeAnimations.degreeVec(-185f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-179.99999999999955f, 20f, -89.99999999999955f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.degreeVec(-185f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("left_arm",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.posVec(-0.28f, 5f, 10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.posVec(-1.51f, 4.35f, 4.33f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.9167f, KeyframeAnimations.posVec(-0.6f, 3.61f, 4.63f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.1667f, KeyframeAnimations.posVec(-0.6f, 3.61f, 0.63f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.6667f, KeyframeAnimations.posVec(-2.85f, -0.1f, 3.33f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.2083f, KeyframeAnimations.posVec(-1f, 0f, 4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.5416765f, KeyframeAnimations.posVec(-1f, 0f, 4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.6766665f, KeyframeAnimations.posVec(0f, -5f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.8343335f, KeyframeAnimations.posVec(-1f, 0f, 4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.0416765f, KeyframeAnimations.posVec(-1f, -5f, 2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.25f, KeyframeAnimations.posVec(-1f, -5f, 2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5f, KeyframeAnimations.posVec(-1f, -10f, 2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.8343335f, KeyframeAnimations.posVec(-1f, -2f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.041677f, KeyframeAnimations.posVec(-1f, -6f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.208343f, KeyframeAnimations.posVec(-5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.375f, KeyframeAnimations.posVec(-1f, -6f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.541677f, KeyframeAnimations.posVec(-5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.posVec(0f, -5f, 2f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("left_arm",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.2917f, KeyframeAnimations.degreeVec(-63.89288f, -0.52011f, 2.09491f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.degreeVec(-63.89288f, -0.52011f, 2.09491f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.degreeVec(-62.87857f, 15.15061f, 9.97445f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.9167f, KeyframeAnimations.degreeVec(-86.93642f, 17.45026f, 4.05284f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.1667f, KeyframeAnimations.degreeVec(-86.93642f, 17.45026f, 4.05284f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.4583f, KeyframeAnimations.degreeVec(-86.93642f, 17.45026f, 4.05284f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.6667f, KeyframeAnimations.degreeVec(63.0984f, 8.83573f, -8.71284f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8333f, KeyframeAnimations.degreeVec(35.5984f, 8.83573f, -8.71284f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.2083f, KeyframeAnimations.degreeVec(-153.27474f, -0.02953f, 3.5235f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.5417f, KeyframeAnimations.degreeVec(-87.07754f, -0.02625f, 3.132f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-156.29763744742513f, 35.82603738046282f, 5.757830407450911f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(-90f, -17.5f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(-168.20592954115864f, 20.448262127520593f, -14.45370892182791f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.25f, KeyframeAnimations.degreeVec(-89.99999913388092f, -10.00000003724108f, 17.499999849600044f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5f, KeyframeAnimations.degreeVec(-182.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.8343335f, KeyframeAnimations.degreeVec(-77.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.041677f, KeyframeAnimations.degreeVec(-185f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.208343f, KeyframeAnimations.degreeVec(-179.99999999999955f, -20f, 89.99999999999955f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.375f, KeyframeAnimations.degreeVec(-185f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-179.99999999999955f, -20f, 89.99999999999955f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.degreeVec(-185f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("right_leg",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -13.98f, -2.37f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.posVec(0f, -13.98f, -2.37f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.3333f, KeyframeAnimations.posVec(0f, -13.98f, -2.37f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5833f, KeyframeAnimations.posVec(0f, -7f, -3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.8333f, KeyframeAnimations.posVec(0f, -9f, -3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.0833f, KeyframeAnimations.posVec(0f, -16.71f, -3.69f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.291677f, KeyframeAnimations.posVec(0f, -19f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -28f, -5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.posVec(0f, -42f, -11f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("right_leg",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.degreeVec(113.27f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.degreeVec(113.27f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.3333f, KeyframeAnimations.degreeVec(113.27f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5833f, KeyframeAnimations.degreeVec(182.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.8333f, KeyframeAnimations.degreeVec(120f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.0833f, KeyframeAnimations.degreeVec(182.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.2917f, KeyframeAnimations.degreeVec(120f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.5f, KeyframeAnimations.degreeVec(157.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.708343f, KeyframeAnimations.degreeVec(102.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.degreeVec(125f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("left_leg",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -14.01f, -2.35f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.posVec(0f, -14.01f, -2.35f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.3333f, KeyframeAnimations.posVec(0f, -14.01f, -2.35f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5833f, KeyframeAnimations.posVec(0f, -5f, -4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.8333f, KeyframeAnimations.posVec(0f, -7f, -4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.0833f, KeyframeAnimations.posVec(0f, -15.5f, -3.76f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.2917f, KeyframeAnimations.posVec(0f, -19f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -28f, -5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.676667f, KeyframeAnimations.posVec(0f, -34f, -4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.posVec(0f, -42f, -11f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("left_leg",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.5f, KeyframeAnimations.degreeVec(114.98f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.7083f, KeyframeAnimations.degreeVec(114.98f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.3333f, KeyframeAnimations.degreeVec(114.98f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.5833f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.8333f, KeyframeAnimations.degreeVec(172.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.0833f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.2917f, KeyframeAnimations.degreeVec(197.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.5f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.676667f, KeyframeAnimations.degreeVec(197.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.958343f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.build();

		WARDEN_EMERGE = AnimationDefinition.Builder.withLength(7.24f)
				.addAnimation("body",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, -63f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.posVec(0f, -56f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.16f, KeyframeAnimations.posVec(0f, -27f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.posVec(0f, -14f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.92f, KeyframeAnimations.posVec(0f, -11f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.08f, KeyframeAnimations.posVec(0f, -14f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.44f, KeyframeAnimations.posVec(0f, -6f, -3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.56f, KeyframeAnimations.posVec(0f, -4f, -3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.68f, KeyframeAnimations.posVec(0f, -6f, -3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.04f, KeyframeAnimations.posVec(0f, -3f, -4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.24f, KeyframeAnimations.posVec(0f, -3f, -4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.44f, KeyframeAnimations.posVec(0f, -3.19f, -5.25f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.64f, KeyframeAnimations.posVec(0f, -3f, -4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.68f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(7.16f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("body",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.degreeVec(25f, 0f, -7.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.92f, KeyframeAnimations.degreeVec(35f, 0f, -7.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.08f, KeyframeAnimations.degreeVec(25f, 0f, -7.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.44f, KeyframeAnimations.degreeVec(47.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.56f, KeyframeAnimations.degreeVec(47.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.68f, KeyframeAnimations.degreeVec(47.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.04f, KeyframeAnimations.degreeVec(70f, 0f, 2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.24f, KeyframeAnimations.degreeVec(70f, 0f, 2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.44f, KeyframeAnimations.degreeVec(79.38f, 0f, 2.66f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.64f, KeyframeAnimations.degreeVec(70f, 0f, 2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.68f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(7.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("head",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.92f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.24f, KeyframeAnimations.posVec(0f, 0.47f, -0.95f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.32f, KeyframeAnimations.posVec(0f, 0.47f, -0.95f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 0.47f, -0.95f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.posVec(0f, 1f, -2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.76f, KeyframeAnimations.posVec(0f, 1f, -2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.84f, KeyframeAnimations.posVec(0f, 1f, -2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.92f, KeyframeAnimations.posVec(0f, 1f, -2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.64f, KeyframeAnimations.posVec(0f, -2f, -2f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.posVec(0f, -4f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.04f, KeyframeAnimations.posVec(0f, -1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.12f, KeyframeAnimations.posVec(0f, -1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.24f, KeyframeAnimations.posVec(0f, -1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.44f, KeyframeAnimations.posVec(0f, -1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.52f, KeyframeAnimations.posVec(0f, -1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.64f, KeyframeAnimations.posVec(0f, -1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5f, KeyframeAnimations.posVec(0f, -1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.08f, KeyframeAnimations.posVec(0f, -1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(7.08f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("head",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.degreeVec(70f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.92f, KeyframeAnimations.degreeVec(0.74f, 0f, -40.38f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.16f, KeyframeAnimations.degreeVec(-67.5f, 0f, -2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.24f, KeyframeAnimations.degreeVec(-67.5f, 0f, -2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.32f, KeyframeAnimations.degreeVec(-47.5f, 0f, -2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.4f, KeyframeAnimations.degreeVec(-67.5f, 0f, -2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.degreeVec(-67.5f, 0f, 15f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.76f, KeyframeAnimations.degreeVec(-67.5f, 0f, -5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.84f, KeyframeAnimations.degreeVec(-52.5f, 0f, -5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.92f, KeyframeAnimations.degreeVec(-67.5f, 0f, -5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.64f, KeyframeAnimations.degreeVec(-17.5f, 0f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.degreeVec(70f, 0f, 12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.04f, KeyframeAnimations.degreeVec(70f, 0f, 12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.12f, KeyframeAnimations.degreeVec(80f, 0f, 12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.24f, KeyframeAnimations.degreeVec(70f, 0f, 12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.44f, KeyframeAnimations.degreeVec(70f, 0f, 12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.52f, KeyframeAnimations.degreeVec(80f, 0f, 12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.64f, KeyframeAnimations.degreeVec(70f, 0f, 12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5f, KeyframeAnimations.degreeVec(77.5f, 0f, -2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.4f, KeyframeAnimations.degreeVec(42.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.08f, KeyframeAnimations.degreeVec(77.5f, 0f, -2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(7.08f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.LINEAR)))
				.addAnimation("right_arm",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.posVec(3f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.posVec(0f, -21f, 9f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.posVec(2f, -2f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8f, KeyframeAnimations.posVec(2f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.posVec(2f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.posVec(2f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.08f, KeyframeAnimations.posVec(2f, -2f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.24f, KeyframeAnimations.posVec(2f, 2.71f, 3.86f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.36f, KeyframeAnimations.posVec(2f, 1f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.posVec(2f, 3f, 3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.08f, KeyframeAnimations.posVec(2f, 3f, 3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.44f, KeyframeAnimations.posVec(2.67f, 4f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.56f, KeyframeAnimations.posVec(2.67f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.68f, KeyframeAnimations.posVec(0f, 4f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.84f, KeyframeAnimations.posVec(0f, 2f, 2.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.04f, KeyframeAnimations.posVec(2f, 0.5f, 4f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.16f, KeyframeAnimations.posVec(2f, 0f, 4.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.56f, KeyframeAnimations.posVec(2f, -1.5f, 6f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6f, KeyframeAnimations.posVec(1.64f, -1.07f, 5.05f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.48f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("right_arm",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.36f, KeyframeAnimations.degreeVec(17.5f, 0f, 22.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, 20f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.degreeVec(-152.5f, 2.5f, 7.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.degreeVec(-180f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8f, KeyframeAnimations.degreeVec(-97.5f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.92f, KeyframeAnimations.degreeVec(-93.62f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.04f, KeyframeAnimations.degreeVec(-90f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.degreeVec(-90f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.56f, KeyframeAnimations.degreeVec(-88.97583863063569f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.72f, KeyframeAnimations.degreeVec(-88.97583863063569f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.degreeVec(-90f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.08f, KeyframeAnimations.degreeVec(-95f, 12.5f, -10f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.24f, KeyframeAnimations.degreeVec(-83.93f, 3.93f, 5.71f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.36f, KeyframeAnimations.degreeVec(-80f, 7.5f, 17.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.degreeVec(-67.5f, 2.5f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.08f, KeyframeAnimations.degreeVec(-67.5f, 2.5f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.44f, KeyframeAnimations.degreeVec(-55f, 2.5f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.56f, KeyframeAnimations.degreeVec(-60f, 2.5f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.68f, KeyframeAnimations.degreeVec(-52.5f, 0f, -5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.84f, KeyframeAnimations.degreeVec(-62.18749999999994f, 1.1225000000000547f, -5.125625000000018f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.04f, KeyframeAnimations.degreeVec(-72.18749999999994f, 1.1225000000000547f, -5.125625000000018f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.16f, KeyframeAnimations.degreeVec(-69.68749999999994f, 1.1225000000000547f, -5.125625000000018f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.6f, KeyframeAnimations.degreeVec(-75.88972091351246f, 2.030500222713836f, -5.12171674263107f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.92f, KeyframeAnimations.degreeVec(-79.93836177589901f, -7.770407293518893f, -5.163902270852068f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.44f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.96f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("left_arm",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.12f, KeyframeAnimations.posVec(0f, -8f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.6f, KeyframeAnimations.posVec(0f, -8f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.posVec(-2f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.posVec(-4f, 3f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8f, KeyframeAnimations.posVec(-4f, 3f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.posVec(-4f, 3f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.posVec(-4f, 3f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.04f, KeyframeAnimations.posVec(-3.23f, 5.7f, 4.97f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.16f, KeyframeAnimations.posVec(-1.49f, 2.22f, 5.25f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.posVec(-1.14f, 1.71f, 1.86f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.92f, KeyframeAnimations.posVec(-1.14f, 1.21f, 3.86f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.08f, KeyframeAnimations.posVec(-1.14f, 2.71f, 4.86f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.44f, KeyframeAnimations.posVec(-1f, 1f, 3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.56f, KeyframeAnimations.posVec(0f, 1f, 1f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.68f, KeyframeAnimations.posVec(0f, 1f, 3f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.84f, KeyframeAnimations.posVec(-0.54f, 4.05f, 1.9699999999999998f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.08f, KeyframeAnimations.posVec(-2f, 1f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.24f, KeyframeAnimations.posVec(-2.12f, 0.6399999999999999f, 5.26f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.56f, KeyframeAnimations.posVec(-2.19f, 0.8899999999999999f, 6.45f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.92f, KeyframeAnimations.posVec(-2f, 3f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.44f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("left_arm",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.12f, KeyframeAnimations.degreeVec(-167.5f, -17.5f, -7.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.6f, KeyframeAnimations.degreeVec(-167.5f, -17.5f, -7.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.88f, KeyframeAnimations.degreeVec(-175f, -17.5f, 15f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.16f, KeyframeAnimations.degreeVec(-190f, -17.5f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.28f, KeyframeAnimations.degreeVec(-95f, -5f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.4f, KeyframeAnimations.degreeVec(-91.72749999999995f, -7.306250000000145f, 0.48499999999989085f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.52f, KeyframeAnimations.degreeVec(-88.28838192419839f, -11.658053935860298f, -5.168775510204268f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.degreeVec(-90f, -17.5f, -12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8f, KeyframeAnimations.degreeVec(-90f, -17.5f, -12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.degreeVec(-90f, -17.5f, -12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.degreeVec(-90f, -17.5f, -12.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.04f, KeyframeAnimations.degreeVec(-81.29f, -10.64f, -14.21f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.16f, KeyframeAnimations.degreeVec(-83.5f, -5.5f, -15.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.degreeVec(-62.5f, -7.5f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.92f, KeyframeAnimations.degreeVec(-58.75f, -3.75f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.08f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.44f, KeyframeAnimations.degreeVec(-52.5f, 0f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.56f, KeyframeAnimations.degreeVec(-50f, 0f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.68f, KeyframeAnimations.degreeVec(-52.5f, 0f, 5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.84f, KeyframeAnimations.degreeVec(-47.18749999999994f, -1.1225000000000547f, 5.125625000000018f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.04f, KeyframeAnimations.degreeVec(-62.18749999999994f, -1.1225000000000547f, 5.125625000000018f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.24f, KeyframeAnimations.degreeVec(-67.51f, -1.15f, 5.27f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.56f, KeyframeAnimations.degreeVec(-71.54f, -1.2f, 5.51f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.84f, KeyframeAnimations.degreeVec(-62.18749999999994f, -1.1225000000000547f, 5.125625000000018f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(7.08f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("right_leg",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, -63f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.posVec(0f, -56f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.36f, KeyframeAnimations.posVec(0f, -22f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.76f, KeyframeAnimations.posVec(0f, -12.28f, 2.48f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.92f, KeyframeAnimations.posVec(0f, -9.28f, 2.48f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.08f, KeyframeAnimations.posVec(0f, -12.28f, 2.48f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.32f, KeyframeAnimations.posVec(0f, -4.14f, 4.14f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.48f, KeyframeAnimations.posVec(0f, -0.57f, -8.43f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.6f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.8f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.64f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("right_leg",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.24f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.84f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.12f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.24f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.44f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.32f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.48f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.64f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("left_leg",
						new AnimationChannel(AnimationChannel.Targets.POSITION,
								new Keyframe(0f, KeyframeAnimations.posVec(0f, -63f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.posVec(0f, -56f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.68f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.8f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.posVec(0f, -32f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.36f, KeyframeAnimations.posVec(0f, -22f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.84f, KeyframeAnimations.posVec(-4f, 2f, -7f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4f, KeyframeAnimations.posVec(-4f, 0f, -5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.36f, KeyframeAnimations.posVec(-4.13f, -0.25f, -7.39f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.52f, KeyframeAnimations.posVec(-4.2f, -0.27f, -6.6899999999999995f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.68f, KeyframeAnimations.posVec(-4f, 0f, -9f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.84f, KeyframeAnimations.posVec(-2f, 2f, -3.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.8f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.64f, KeyframeAnimations.posVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.addAnimation("left_leg",
						new AnimationChannel(AnimationChannel.Targets.ROTATION,
								new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.24f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.52f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(0.84f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(2.88f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3f, KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.24f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(3.84f, KeyframeAnimations.degreeVec(20f, 0f, -17.5f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.36f, KeyframeAnimations.degreeVec(10.22f, 0f, 1.03f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.52f, KeyframeAnimations.degreeVec(11.370000000000001f, 0f, 0.58f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.68f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(4.84f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(5.8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM),
								new Keyframe(6.64f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
										AnimationChannel.Interpolations.CATMULLROM)))
				.build();

		if (WilderSharedConstants.CONFIG().wardenBedrockSniff()) {
			WARDEN_SNIFF = AnimationDefinition.Builder.withLength(4.16F)
					.addAnimation(
							"body",
							new AnimationChannel(
									AnimationChannel.Targets.ROTATION,
									new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(0.56F, KeyframeAnimations.degreeVec(17.5F, 32.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(0.96F, KeyframeAnimations.degreeVec(0.0F, 32.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.2F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.8F, KeyframeAnimations.degreeVec(10.0F, -30.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM))
					)
					.addAnimation(
							"head",
							new AnimationChannel(
									AnimationChannel.Targets.ROTATION,
									new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, 40.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(0.96F, KeyframeAnimations.degreeVec(-22.5F, 40.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(1.24F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(1.52F, KeyframeAnimations.degreeVec(-35.0F, 20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(1.76F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.28F, KeyframeAnimations.degreeVec(0.0F, -20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.6F, KeyframeAnimations.degreeVec(WilderSharedConstants.CONFIG().wardenBedrockSniff() ? -25.0F : 0.0F, -23.6504F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.88F, KeyframeAnimations.degreeVec(0.0F, -20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)))
					.addAnimation(
							"right_arm",
							new AnimationChannel(
									AnimationChannel.Targets.ROTATION,
									new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(0.96F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.76F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)))
					.addAnimation(
							"left_arm",
							new AnimationChannel(
									AnimationChannel.Targets.ROTATION,
									new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(0.96F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(2.76F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
									new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)))
					.build();
		}
	}

}
