/*
 * Copyright 2023-2024 FrozenBlock
 * This file is part of Wilder Wild.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, see <https://www.gnu.org/licenses/>.
 */

package net.frozenblock.wilderwild.client.animation.definitions;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

@Environment(EnvType.CLIENT)
public final class CrabAnimation {

	public static final AnimationDefinition CRAB_DIG = AnimationDefinition.Builder.withLength(4.75f)
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, 0f, 1f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.posVec(0f, -0.34f, 1f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -2.25f, 1f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75f, KeyframeAnimations.posVec(0f, -3f, 1f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -7f, 1f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(15f, 0f, 3f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(50f, 0f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(40f, 0f, -2f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75f, KeyframeAnimations.degreeVec(17f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-20.28f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(-21.39f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.25f, KeyframeAnimations.degreeVec(-23.09f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(-24.45f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.625f, KeyframeAnimations.degreeVec(-26.14f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(-31.12f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.125f, KeyframeAnimations.degreeVec(-34.32f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.375f, KeyframeAnimations.degreeVec(-37.17f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5f, KeyframeAnimations.degreeVec(-38.6f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(-40.97f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.875f, KeyframeAnimations.degreeVec(-42.87f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-45.25f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25f, KeyframeAnimations.degreeVec(-47.15f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.degreeVec(-50f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625f, KeyframeAnimations.degreeVec(-50.83f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75f, KeyframeAnimations.degreeVec(-51.67f, 1.25f, -1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8343335f, KeyframeAnimations.degreeVec(-52.39f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4f, KeyframeAnimations.degreeVec(-53.84f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.208343f, KeyframeAnimations.degreeVec(-56.01f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.375f, KeyframeAnimations.degreeVec(-57.1f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.583433f, KeyframeAnimations.degreeVec(-58.91f, -2.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.degreeVec(-60f, 2.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.SCALE,
				new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.08343333f, KeyframeAnimations.posVec(-0.75f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334f, KeyframeAnimations.posVec(-1f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.posVec(-1.25f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434f, KeyframeAnimations.posVec(-1.25f, 0f, -1.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8343334f, KeyframeAnimations.posVec(-1.25f, 0f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(-1.25f, -1f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1f, KeyframeAnimations.posVec(-1.25f, -1f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 27.5f, 35f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 50f, 35f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 55f, 35f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 55f, 35f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.25f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.625f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.375f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.75f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9167665f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2083435f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5834335f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.6766665f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.7916765f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8343335f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.875f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.041677f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.208343f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.25f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.343333f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.416767f, KeyframeAnimations.degreeVec(170f, 157.5f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677f, KeyframeAnimations.degreeVec(132.5f, 15f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.583433f, KeyframeAnimations.degreeVec(132.5f, 45f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.625f, KeyframeAnimations.degreeVec(132.5f, 72.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.degreeVec(132.5f, 157.5f, 50f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.SCALE,
				new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("legs",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("legs",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 27.5f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_bottom",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_bottom",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0.08343333f, KeyframeAnimations.posVec(0.75f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.posVec(0.91f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.posVec(1.14f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.posVec(1.14f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75f, KeyframeAnimations.posVec(1.14f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -27.5f, -35f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, -50f, -35f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, -55f, -35f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, -55f, -35f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.75f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.125f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2083435f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.7916765f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.875f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2083435f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5416765f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5834335f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.7916765f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.083433f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.343333f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.375f, KeyframeAnimations.degreeVec(132.5f, -72.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.458343f, KeyframeAnimations.degreeVec(132.5f, -157.5f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677f, KeyframeAnimations.degreeVec(170f, -157.5f, 2.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.676667f, KeyframeAnimations.degreeVec(132.5f, -15f, -50f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.degreeVec(132.5f, -45f, -50f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 1f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 1.5f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 1.5f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, -1f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665f, KeyframeAnimations.posVec(0f, -1.75f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -1.75f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665f, KeyframeAnimations.posVec(0f, -1f, 1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -1.75f, 1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, -3.12f, 0.66f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -5f, -1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75f, KeyframeAnimations.posVec(0f, -5.25f, -1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -9.75f, -3.75f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.degreeVec(-7.5f, 0f, -18.57f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.25f, KeyframeAnimations.degreeVec(-20f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-20f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5f, KeyframeAnimations.degreeVec(-27.5f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-37.5f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-37.5f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-62.5f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(-72.5f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.25f, KeyframeAnimations.degreeVec(-72.5f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(-59.61f, 3.23f, -28.66f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(-46.11f, 5.74f, -21.3f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5f, KeyframeAnimations.degreeVec(-37.5f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.degreeVec(-80f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75f, KeyframeAnimations.degreeVec(-95.92f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.degreeVec(-143.42f, 0f, -32.5f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, -0.25f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 1f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 1.5f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, 1.5f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, -1f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.posVec(0f, -1.75f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665f, KeyframeAnimations.posVec(0f, -1.75f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.3433335f, KeyframeAnimations.posVec(0f, -1f, 1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665f, KeyframeAnimations.posVec(0f, -1.75f, 1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4583435f, KeyframeAnimations.posVec(0f, -3.12f, 0.66f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -5f, -1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75f, KeyframeAnimations.posVec(0f, -5.25f, -1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -9.75f, -3.75f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-19.81f, -0.02f, 16.06f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-20f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.375f, KeyframeAnimations.degreeVec(-20f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-27.5f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75f, KeyframeAnimations.degreeVec(-37.5f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-37.5f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-62.5f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(-72.5f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(-72.5f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.25f, KeyframeAnimations.degreeVec(-59.61f, -3.23f, 28.66f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(-46.11f, -5.74f, 21.3f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(-37.5f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.degreeVec(-80f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75f, KeyframeAnimations.degreeVec(-95.92f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.degreeVec(-143.42f, 0f, 32.5f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 1f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0.75f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0.75f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.posVec(0f, -0.25f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.625f, KeyframeAnimations.posVec(0f, -0.25f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -0.25f, 1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335f, KeyframeAnimations.posVec(0f, -1.75f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625f, KeyframeAnimations.posVec(0f, -3.25f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667f, KeyframeAnimations.posVec(0f, -5f, -1.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -7f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-7.5f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-7.5f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-30f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(-40f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.625f, KeyframeAnimations.degreeVec(-40f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.75f, KeyframeAnimations.degreeVec(-20f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(-35f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125f, KeyframeAnimations.degreeVec(-50f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625f, KeyframeAnimations.degreeVec(-67.5f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667f, KeyframeAnimations.degreeVec(-87.5f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.degreeVec(-117.5f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 1f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0.75f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0.75f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.posVec(0f, -0.25f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665f, KeyframeAnimations.posVec(0f, -0.25f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, -0.25f, 1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.625f, KeyframeAnimations.posVec(0f, -1.75f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625f, KeyframeAnimations.posVec(0f, -3.25f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667f, KeyframeAnimations.posVec(0f, -5f, -1.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -7f, -2.5f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-7.5f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-7.5f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-30f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(-40f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(-40f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765f, KeyframeAnimations.degreeVec(-20f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.625f, KeyframeAnimations.degreeVec(-35f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125f, KeyframeAnimations.degreeVec(-50f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625f, KeyframeAnimations.degreeVec(-67.5f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667f, KeyframeAnimations.degreeVec(-87.5f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.degreeVec(-117.5f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 1.58f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, 0.75f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335f, KeyframeAnimations.posVec(0f, 0.5f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.1676665f, KeyframeAnimations.posVec(0f, 1.75f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2916765f, KeyframeAnimations.posVec(0f, 0f, -0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435f, KeyframeAnimations.posVec(0f, -2.25f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677f, KeyframeAnimations.posVec(0f, -3.5f, -0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677f, KeyframeAnimations.posVec(0f, -4.5f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -6f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-7.5f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-15.16f, -3.41f, 11.34f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(7.5f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25f, KeyframeAnimations.degreeVec(-20f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(-32.5f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.degreeVec(-45.83f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(-78.33f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677f, KeyframeAnimations.degreeVec(-110.83f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-133.33f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.041676664f, KeyframeAnimations.posVec(0f, 1.58f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, 0.75f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9167665f, KeyframeAnimations.posVec(0f, 0.5f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3f, KeyframeAnimations.posVec(0f, 1.75f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335f, KeyframeAnimations.posVec(0f, 1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125f, KeyframeAnimations.posVec(0f, 0f, -0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435f, KeyframeAnimations.posVec(0f, -2.25f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677f, KeyframeAnimations.posVec(0f, -3.5f, -0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677f, KeyframeAnimations.posVec(0f, -4.5f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343f, KeyframeAnimations.posVec(0f, -6f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-7.5f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9167665f, KeyframeAnimations.degreeVec(-15.16f, 3.41f, -11.34f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3f, KeyframeAnimations.degreeVec(7.5f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-20f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125f, KeyframeAnimations.degreeVec(-32.5f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5f, KeyframeAnimations.degreeVec(-45.83f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(-78.33f, 0f, -15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677f, KeyframeAnimations.degreeVec(-110.83f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-133.33f, 0f, 15f),
					AnimationChannel.Interpolations.CATMULLROM))).build();

	public static final AnimationDefinition CRAB_EMERGE = AnimationDefinition.Builder.withLength(1.5f)
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, -1f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 1f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(0f, 0f, -1f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(0f, 0f, 1f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, -1f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(1f, -11f, -1f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666f, KeyframeAnimations.posVec(1f, -4f, -1f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.posVec(1f, -3f, -1f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5416766f, KeyframeAnimations.posVec(1f, -3f, -1f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625f, KeyframeAnimations.posVec(1f, -2f, -1.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.posVec(1f, -2f, -0.75f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434f, KeyframeAnimations.posVec(1f, -2f, -0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.posVec(1f, -0.75f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(106.46f, 24.89f, 223.04f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(129.73f, -12.27f, 199.94f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.375f, KeyframeAnimations.degreeVec(184.1f, -26.91f, 138.8f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(172.39f, -26.76f, 151.52f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(172.39f, -26.76f, 151.52f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625f, KeyframeAnimations.degreeVec(200.99f, -30.45f, 122.53f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(212.33f, -28.5f, 110.46f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(231.74f, -19.99f, 89.01f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 360f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(-1f, -11f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, -4f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.posVec(-1f, -3f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5416766f, KeyframeAnimations.posVec(-1f, -3f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625f, KeyframeAnimations.posVec(-1f, -2f, -0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.posVec(-1f, -2f, 0.25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434f, KeyframeAnimations.posVec(-1f, -2f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.posVec(-1f, -0.75f, 0.5f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(106.46f, -24.89f, -223.04f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(129.73f, 12.27f, -199.93f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.375f, KeyframeAnimations.degreeVec(184.1f, 26.91f, -138.8f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(172.39f, 26.76f, -151.52f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(172.39f, 26.76f, -151.52f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625f, KeyframeAnimations.degreeVec(200.99f, 30.45f, -122.53f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(212.33f, 28.5f, -110.46f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(231.74f, 19.99f, -89.01f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, -360f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, -6f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, -2f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, -1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.625f, KeyframeAnimations.degreeVec(44.38f, -32.03f, 14.64f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75f, KeyframeAnimations.degreeVec(-1.97f, -37.33f, 12.84f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875f, KeyframeAnimations.degreeVec(-6.16f, -29.97f, -2.05f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1f, KeyframeAnimations.degreeVec(-0.33f, -17.16f, 7.89f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, -6f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, -2f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, -1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(19.38f, 32.03f, -14.64f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-1.97f, 37.33f, -12.84f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-6.16f, 29.97f, 2.05f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(-0.33f, 17.16f, -7.89f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, -4.49f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, -2f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, -25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-16.77f, 18.66f, 20.05f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-20f, -17.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(-20f, -17.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125f, KeyframeAnimations.degreeVec(-11.51f, -11.62f, 22.09f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, -4.49f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, -2f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875f, KeyframeAnimations.degreeVec(-16.77f, -18.66f, -20.05f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1f, KeyframeAnimations.degreeVec(-20f, 17.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-20f, 17.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(-11.51f, 11.62f, -22.09f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, -5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0.15f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433f, KeyframeAnimations.posVec(0f, 0.15f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(13.59f, -13.18f, 10.16f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1f, KeyframeAnimations.degreeVec(-5.99f, -8.88f, 18.21f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-9.38f, -34.49f, -10.85f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.25f, KeyframeAnimations.degreeVec(-6.09f, -4.67f, 6.42f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, -5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0.15f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433f, KeyframeAnimations.posVec(0f, 0.15f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(13.59f, 13.18f, -10.16f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(-5.99f, 8.88f, -18.21f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125f, KeyframeAnimations.degreeVec(-9.38f, 34.49f, 10.85f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(-6.09f, 4.67f, -6.42f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("torso",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, -7f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, -5f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, -3f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, -1f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("torso",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(34.36f, 7.13f, -10.29f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(12.45f, -1.08f, 4.88f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-1.25f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1f, KeyframeAnimations.degreeVec(-0.25f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM))).build();

	public static final AnimationDefinition CRAB_EMERGE_WAIT = AnimationDefinition.Builder.withLength(0.0f)
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(1f, -11f, -1f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(106.46f, 24.89f, 223.04f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(-1f, -11f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(106.46f, -24.89f, -223.04f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("torso",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, 0f),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("torso",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.CATMULLROM))).build();
}
