/*
 * Copyright 2025 FrozenBlock
 * This file is part of Wilder Wild.
 *
 * This program is free software; you can modify it under
 * the terms of version 1 of the FrozenBlock Modding Oasis License
 * as published by FrozenBlock Modding Oasis.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * FrozenBlock Modding Oasis License for more details.
 *
 * You should have received a copy of the FrozenBlock Modding Oasis License
 * along with this program; if not, see <https://github.com/FrozenBlock/Licenses>.
 */

package net.frozenblock.wilderwild.client.animation.definitions;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

@Environment(EnvType.CLIENT)
public final class CrabAnimation {
	public static final AnimationDefinition CRAB_DIG = AnimationDefinition.Builder.withLength(4.75F)
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.posVec(0F, 0F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.posVec(0F, -0.34F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.posVec(0F, -2.25F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75F, KeyframeAnimations.posVec(0F, -3F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.posVec(0F, -7F, 1F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(2.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.08343333F, KeyframeAnimations.degreeVec(15F, 0F, 3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.degreeVec(45F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433F, KeyframeAnimations.degreeVec(50F, 0F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5834334F, KeyframeAnimations.degreeVec(40F, 0F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(17F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(-20.28F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767F, KeyframeAnimations.degreeVec(-21.39F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.25F, KeyframeAnimations.degreeVec(-23.09F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4167667F, KeyframeAnimations.degreeVec(-24.45F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.625F, KeyframeAnimations.degreeVec(-26.14F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.degreeVec(-27.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.9583433F, KeyframeAnimations.degreeVec(-31.12F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.125F, KeyframeAnimations.degreeVec(-34.32F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.375F, KeyframeAnimations.degreeVec(-37.17F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5F, KeyframeAnimations.degreeVec(-38.6F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.7083435F, KeyframeAnimations.degreeVec(-40.97F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.875F, KeyframeAnimations.degreeVec(-42.87F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.degreeVec(-45.25F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25F, KeyframeAnimations.degreeVec(-47.15F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.degreeVec(-50F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625F, KeyframeAnimations.degreeVec(-50.83F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75F, KeyframeAnimations.degreeVec(-51.67F, 1.25F, -1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8343335F, KeyframeAnimations.degreeVec(-52.39F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4F, KeyframeAnimations.degreeVec(-53.84F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.208343F, KeyframeAnimations.degreeVec(-56.01F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.375F, KeyframeAnimations.degreeVec(-57.1F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.583433F, KeyframeAnimations.degreeVec(-58.91F, -2.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.degreeVec(-60F, 2.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.SCALE,
				new Keyframe(0F, KeyframeAnimations.scaleVec(1F, 1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.08343333F, KeyframeAnimations.posVec(-0.75F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334F, KeyframeAnimations.posVec(-1F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.posVec(-1.25F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434F, KeyframeAnimations.posVec(-1.25F, 0F, -1.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8343334F, KeyframeAnimations.posVec(-1.25F, 0F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(-1.25F, -1F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.posVec(-1.25F, -1F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.degreeVec(0F, 27.5F, 35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.degreeVec(0F, 50F, 35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3433333F, KeyframeAnimations.degreeVec(0F, 55F, 35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5834334F, KeyframeAnimations.degreeVec(0F, 55F, 35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8343334F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1676667F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.25F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4167667F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5416767F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5834333F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.625F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7083433F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.9167667F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.9583433F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.3433335F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.375F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4583435F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6766665F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.7083435F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.75F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9167665F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0416765F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2083435F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2916765F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.4167665F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.4583435F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5834335F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.6766665F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.7916765F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8343335F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.875F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.041677F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.208343F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.25F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.343333F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.416767F, KeyframeAnimations.degreeVec(170F, 157.5F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.degreeVec(132.5F, 15F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.583433F, KeyframeAnimations.degreeVec(132.5F, 45F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.625F, KeyframeAnimations.degreeVec(132.5F, 72.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.degreeVec(132.5F, 157.5F, 50F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.SCALE,
				new Keyframe(0F, KeyframeAnimations.scaleVec(1F, 1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("legs",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("legs",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.degreeVec(17.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0.4167667F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0.4167667F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8343334F, KeyframeAnimations.degreeVec(0F, 0F, 27.5F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_bottom",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0.9583434F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_bottom",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0.875F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.degreeVec(0F, 0F, -5F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0.08343333F, KeyframeAnimations.posVec(0.75F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.posVec(0.91F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.posVec(1.14F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.posVec(1.14F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.posVec(1.14F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.degreeVec(0F, -27.5F, -35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.degreeVec(0F, -50F, -35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3433333F, KeyframeAnimations.degreeVec(0F, -55F, -35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5834334F, KeyframeAnimations.degreeVec(0F, -55F, -35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0834333F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1676667F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2916767F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4583433F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5416767F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6766667F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7083433F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.75F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8343333F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.9167667F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0416765F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.125F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2083435F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4583435F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5834335F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6766665F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.7916765F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.875F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9583435F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0416765F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.1676665F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2083435F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.3433335F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.4167665F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5416765F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5834335F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.7083435F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.7916765F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9167665F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.083433F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.343333F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.375F, KeyframeAnimations.degreeVec(132.5F, -72.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.458343F, KeyframeAnimations.degreeVec(132.5F, -157.5F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.degreeVec(170F, -157.5F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.676667F, KeyframeAnimations.degreeVec(132.5F, -15F, -50F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.degreeVec(132.5F, -45F, -50F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.posVec(0F, 0F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.25F, KeyframeAnimations.posVec(0F, 1F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3433333F, KeyframeAnimations.posVec(0F, 1.5F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.posVec(0F, 1.5F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434F, KeyframeAnimations.posVec(0F, 0F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 0F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.posVec(0F, -1F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665F, KeyframeAnimations.posVec(0F, -1.75F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.25F, KeyframeAnimations.posVec(0F, -1.75F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665F, KeyframeAnimations.posVec(0F, -1F, 1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5F, KeyframeAnimations.posVec(0F, -1.75F, 1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.posVec(0F, -3.12F, 0.66F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.posVec(0F, -5F, -1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75F, KeyframeAnimations.posVec(0F, -5.25F, -1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.posVec(0F, -9.75F, -3.75F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.degreeVec(-7.5F, 0F, -18.57F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.25F, KeyframeAnimations.degreeVec(-20F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.3433333F, KeyframeAnimations.degreeVec(-20F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.degreeVec(-27.5F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434F, KeyframeAnimations.degreeVec(-37.5F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(-37.5F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.degreeVec(-62.5F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665F, KeyframeAnimations.degreeVec(-72.5F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.25F, KeyframeAnimations.degreeVec(-72.5F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.3433335F, KeyframeAnimations.degreeVec(-59.61F, 3.23F, -28.66F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665F, KeyframeAnimations.degreeVec(-46.11F, 5.74F, -21.3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5F, KeyframeAnimations.degreeVec(-37.5F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.degreeVec(-80F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75F, KeyframeAnimations.degreeVec(-95.92F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.degreeVec(-143.42F, 0F, -32.5F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666F, KeyframeAnimations.posVec(0F, -0.25F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.posVec(0F, 1F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.375F, KeyframeAnimations.posVec(0F, 1.5F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5416766F, KeyframeAnimations.posVec(0F, 1.5F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.posVec(0F, 0F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.posVec(0F, 0F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.posVec(0F, -1F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.posVec(0F, -1.75F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665F, KeyframeAnimations.posVec(0F, -1.75F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.3433335F, KeyframeAnimations.posVec(0F, -1F, 1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665F, KeyframeAnimations.posVec(0F, -1.75F, 1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4583435F, KeyframeAnimations.posVec(0F, -3.12F, 0.66F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.posVec(0F, -5F, -1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75F, KeyframeAnimations.posVec(0F, -5.25F, -1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.posVec(0F, -9.75F, -3.75F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666F, KeyframeAnimations.degreeVec(-19.81F, -0.02F, 16.06F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.degreeVec(-20F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.375F, KeyframeAnimations.degreeVec(-20F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5416766F, KeyframeAnimations.degreeVec(-27.5F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(-37.5F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.degreeVec(-37.5F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.degreeVec(-62.5F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.degreeVec(-72.5F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.1676665F, KeyframeAnimations.degreeVec(-72.5F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.25F, KeyframeAnimations.degreeVec(-59.61F, -3.23F, 28.66F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.3433335F, KeyframeAnimations.degreeVec(-46.11F, -5.74F, 21.3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665F, KeyframeAnimations.degreeVec(-37.5F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.degreeVec(-80F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75F, KeyframeAnimations.degreeVec(-95.92F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.degreeVec(-143.42F, 0F, 32.5F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.posVec(0F, 0F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666F, KeyframeAnimations.posVec(0F, 0F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.posVec(0F, 1F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.posVec(0F, 0.75F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 0.75F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.posVec(0F, 0.25F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.posVec(0F, -0.25F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.625F, KeyframeAnimations.posVec(0F, -0.25F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.75F, KeyframeAnimations.posVec(0F, -0.25F, 1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335F, KeyframeAnimations.posVec(0F, -1.75F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125F, KeyframeAnimations.posVec(0F, -2.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625F, KeyframeAnimations.posVec(0F, -3.25F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667F, KeyframeAnimations.posVec(0F, -5F, -1.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.posVec(0F, -7F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.degreeVec(-7.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.degreeVec(-7.5F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(-7.5F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.degreeVec(-30F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.degreeVec(-40F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.625F, KeyframeAnimations.degreeVec(-40F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.75F, KeyframeAnimations.degreeVec(-20F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335F, KeyframeAnimations.degreeVec(-35F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125F, KeyframeAnimations.degreeVec(-50F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625F, KeyframeAnimations.degreeVec(-67.5F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667F, KeyframeAnimations.degreeVec(-87.5F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.degreeVec(-117.5F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.posVec(0F, 0F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666F, KeyframeAnimations.posVec(0F, 0F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.posVec(0F, 1F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.posVec(0F, 0.75F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 0.75F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.posVec(0F, 0.25F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.posVec(0F, -0.25F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665F, KeyframeAnimations.posVec(0F, -0.25F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.posVec(0F, -0.25F, 1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.625F, KeyframeAnimations.posVec(0F, -1.75F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125F, KeyframeAnimations.posVec(0F, -2.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625F, KeyframeAnimations.posVec(0F, -3.25F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667F, KeyframeAnimations.posVec(0F, -5F, -1.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.posVec(0F, -7F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.degreeVec(-7.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.degreeVec(-7.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(-7.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.degreeVec(-30F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.0834335F, KeyframeAnimations.degreeVec(-40F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4167665F, KeyframeAnimations.degreeVec(-40F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.degreeVec(-20F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.625F, KeyframeAnimations.degreeVec(-35F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125F, KeyframeAnimations.degreeVec(-50F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625F, KeyframeAnimations.degreeVec(-67.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.167667F, KeyframeAnimations.degreeVec(-87.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.degreeVec(-117.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.posVec(0F, 1.58F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334F, KeyframeAnimations.posVec(0F, 1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.posVec(0F, 0.75F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.posVec(0F, 0.5F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.1676665F, KeyframeAnimations.posVec(0F, 1.75F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25F, KeyframeAnimations.posVec(0F, 1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2916765F, KeyframeAnimations.posVec(0F, 0F, -0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.posVec(0F, -0.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435F, KeyframeAnimations.posVec(0F, -2.25F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677F, KeyframeAnimations.posVec(0F, -3.5F, -0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.posVec(0F, -4.5F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.posVec(0F, -6F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334F, KeyframeAnimations.degreeVec(0F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(0F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.degreeVec(-7.5F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.degreeVec(-15.16F, -3.41F, 11.34F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.1676665F, KeyframeAnimations.degreeVec(7.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25F, KeyframeAnimations.degreeVec(-20F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2916765F, KeyframeAnimations.degreeVec(-32.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.degreeVec(-45.83F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435F, KeyframeAnimations.degreeVec(-78.33F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677F, KeyframeAnimations.degreeVec(-110.83F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.degreeVec(-133.33F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.041676664F, KeyframeAnimations.posVec(0F, 1.58F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.posVec(0F, 1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.posVec(0F, 0.75F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9167665F, KeyframeAnimations.posVec(0F, 0.5F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3F, KeyframeAnimations.posVec(0F, 1.75F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.posVec(0F, 1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125F, KeyframeAnimations.posVec(0F, 0F, -0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.posVec(0F, -0.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435F, KeyframeAnimations.posVec(0F, -2.25F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677F, KeyframeAnimations.posVec(0F, -3.5F, -0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.posVec(0F, -4.5F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.posVec(0F, -6F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.125F, KeyframeAnimations.degreeVec(0F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(0F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.7916767F, KeyframeAnimations.degreeVec(-7.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9167665F, KeyframeAnimations.degreeVec(-15.16F, 3.41F, -11.34F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3F, KeyframeAnimations.degreeVec(7.5F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.degreeVec(-20F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.125F, KeyframeAnimations.degreeVec(-32.5F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.degreeVec(-45.83F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.9583435F, KeyframeAnimations.degreeVec(-78.33F, 0F, -15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677F, KeyframeAnimations.degreeVec(-110.83F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.degreeVec(-133.33F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM))).build();

	public static final AnimationDefinition CRAB_EMERGE = AnimationDefinition.Builder.withLength(1.5F)
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8343334F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.8343334F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(0F, 0F, -1F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1F, KeyframeAnimations.degreeVec(0F, 0F, 1F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.0834333F, KeyframeAnimations.degreeVec(0F, 0F, -1F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.1676667F, KeyframeAnimations.degreeVec(0F, 0F, 1F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.25F, KeyframeAnimations.degreeVec(0F, 0F, -1F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.3433333F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(1F, -11F, -1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666F, KeyframeAnimations.posVec(1F, -4F, -1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.posVec(1F, -3F, -1F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5416766F, KeyframeAnimations.posVec(1F, -3F, -1F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625F, KeyframeAnimations.posVec(1F, -2F, -1.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.posVec(1F, -2F, -0.75F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434F, KeyframeAnimations.posVec(1F, -2F, -0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.posVec(1F, -0.75F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(106.46F, 24.89F, 223.04F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.degreeVec(129.73F, -12.27F, 199.94F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.375F, KeyframeAnimations.degreeVec(184.1F, -26.91F, 138.8F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433F, KeyframeAnimations.degreeVec(172.39F, -26.76F, 151.52F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5416766F, KeyframeAnimations.degreeVec(172.39F, -26.76F, 151.52F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625F, KeyframeAnimations.degreeVec(200.99F, -30.45F, 122.53F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.degreeVec(212.33F, -28.5F, 110.46F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.degreeVec(231.74F, -19.99F, 89.01F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375F, KeyframeAnimations.degreeVec(0F, 0F, 360F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(-1F, -11F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16766666F, KeyframeAnimations.posVec(0F, -4F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.posVec(-1F, -3F, 0F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5416766F, KeyframeAnimations.posVec(-1F, -3F, 0F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625F, KeyframeAnimations.posVec(-1F, -2F, -0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.posVec(-1F, -2F, 0.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434F, KeyframeAnimations.posVec(-1F, -2F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.posVec(-1F, -0.75F, 0.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(106.46F, -24.89F, -223.04F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2916767F, KeyframeAnimations.degreeVec(129.73F, 12.27F, -199.93F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.375F, KeyframeAnimations.degreeVec(184.1F, 26.91F, -138.8F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433F, KeyframeAnimations.degreeVec(172.39F, 26.76F, -151.52F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.5416766F, KeyframeAnimations.degreeVec(172.39F, 26.76F, -151.52F),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.625F, KeyframeAnimations.degreeVec(200.99F, 30.45F, -122.53F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.degreeVec(212.33F, 28.5F, -110.46F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.degreeVec(231.74F, 19.99F, -89.01F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.375F, KeyframeAnimations.degreeVec(0F, 0F, -360F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.posVec(0F, -6F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.posVec(0F, -2F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.posVec(0F, -1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.625F, KeyframeAnimations.degreeVec(44.38F, -32.03F, 14.64F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(-1.97F, -37.33F, 12.84F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875F, KeyframeAnimations.degreeVec(-6.16F, -29.97F, -2.05F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(-0.33F, -17.16F, 7.89F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0834333F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.posVec(0F, -6F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.posVec(0F, -2F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.posVec(0F, -1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.degreeVec(19.38F, 32.03F, -14.64F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.degreeVec(-1.97F, 37.33F, -12.84F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(-6.16F, 29.97F, 2.05F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767F, KeyframeAnimations.degreeVec(-0.33F, 17.16F, -7.89F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433F, KeyframeAnimations.posVec(0F, -4.49F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434F, KeyframeAnimations.posVec(0F, -2F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.degreeVec(0F, 0F, -25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8343334F, KeyframeAnimations.degreeVec(-16.77F, 18.66F, 20.05F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.degreeVec(-20F, -17.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767F, KeyframeAnimations.degreeVec(-20F, -17.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125F, KeyframeAnimations.degreeVec(-11.51F, -11.62F, 22.09F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4583433F, KeyframeAnimations.posVec(0F, -4.49F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434F, KeyframeAnimations.posVec(0F, -2F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083434F, KeyframeAnimations.degreeVec(0F, 0F, 25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.875F, KeyframeAnimations.degreeVec(-16.77F, -18.66F, -20.05F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(-20F, 17.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0834333F, KeyframeAnimations.degreeVec(-20F, 17.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1676667F, KeyframeAnimations.degreeVec(-11.51F, 11.62F, -22.09F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.25F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.posVec(0F, -5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.posVec(0F, -2.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.posVec(0F, 0.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125F, KeyframeAnimations.posVec(0F, 0.15F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433F, KeyframeAnimations.posVec(0F, 0.15F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.75F, KeyframeAnimations.degreeVec(2.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(13.59F, -13.18F, 10.16F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(-5.99F, -8.88F, 18.21F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0834333F, KeyframeAnimations.degreeVec(-9.38F, -34.49F, -10.85F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.25F, KeyframeAnimations.degreeVec(-6.09F, -4.67F, 6.42F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2916767F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.posVec(0F, -5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.posVec(0F, -2.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.posVec(0F, 0.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125F, KeyframeAnimations.posVec(0F, 0.15F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433F, KeyframeAnimations.posVec(0F, 0.15F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.degreeVec(2.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9583434F, KeyframeAnimations.degreeVec(13.59F, 13.18F, -10.16F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767F, KeyframeAnimations.degreeVec(-5.99F, 8.88F, -18.21F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.125F, KeyframeAnimations.degreeVec(-9.38F, 34.49F, 10.85F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2916767F, KeyframeAnimations.degreeVec(-6.09F, 4.67F, -6.42F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.5F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("torso",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.posVec(0F, -7F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5416766F, KeyframeAnimations.posVec(0F, -5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.posVec(0F, -3F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.posVec(0F, -1F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("torso",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.20834334F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4167667F, KeyframeAnimations.degreeVec(34.36F, 7.13F, -10.29F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5416766F, KeyframeAnimations.degreeVec(55F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.degreeVec(35F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7916766F, KeyframeAnimations.degreeVec(12.45F, -1.08F, 4.88F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167666F, KeyframeAnimations.degreeVec(-1.25F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(-0.25F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0416767F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM))).build();

	public static final AnimationDefinition CRAB_EMERGE_WAIT = AnimationDefinition.Builder.withLength(0.0F)
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(1F, -11F, -1F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(106.46F, 24.89F, 223.04F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(-1F, -11F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("main_claw",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(106.46F, -24.89F, -223.04F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("claw_top",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("front_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("middle_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("back_right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("torso",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -9F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("torso",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM))).build();
}
