/*
 * Copyright 2025 FrozenBlock
 * This file is part of Wilder Wild.
 *
 * This program is free software; you can modify it under
 * the terms of version 1 of the FrozenBlock Modding Oasis License
 * as published by FrozenBlock Modding Oasis.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * FrozenBlock Modding Oasis License for more details.
 *
 * You should have received a copy of the FrozenBlock Modding Oasis License
 * along with this program; if not, see <https://github.com/FrozenBlock/Licenses>.
 */

package net.frozenblock.wilderwild.client.animation.definitions;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.frozenblock.wilderwild.config.WWEntityConfig;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.AnimationDefinition.Builder;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

/**
 * Put custom Warden animations in here. for example, death, flying, swimming. Not for overrides.
 */
@Environment(EnvType.CLIENT)
public final class WWWardenAnimation {
	public static final AnimationDefinition WARDEN_DIG = AnimationDefinition.Builder.withLength(5.167667F)
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.posVec(0F, -16.48454F, -6.5784F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.posVec(0F, -16.48454F, -6.5784F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0417F, KeyframeAnimations.posVec(0F, -16.97F, -7.11F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.625F, KeyframeAnimations.posVec(0F, -13.97F, -7.11F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2083F, KeyframeAnimations.posVec(0F, -11.48454F, -0.5784F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5417F, KeyframeAnimations.posVec(0F, -16.48454F, -6.5784F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6667F, KeyframeAnimations.posVec(0F, -20.27F, -5.42F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.375F, KeyframeAnimations.posVec(0F, -21.48454F, -5.5784F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.0417F, KeyframeAnimations.posVec(0F, -22.48454F, -5.5784F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.5F, KeyframeAnimations.posVec(0F, -40F, -8F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.posVec(0F, -51F, -18F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.25F, KeyframeAnimations.degreeVec(4.13441F, 0.94736F, 1.2694F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.degreeVec(50F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.degreeVec(54.45407F, -13.53935F, -18.14183F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0417F, KeyframeAnimations.degreeVec(39.46442000000045F, -10.8885F, 35.7954F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3333F, KeyframeAnimations.degreeVec(52.282610000000005F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.625F, KeyframeAnimations.degreeVec(53.23606F, 10.04715F, -29.72932F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2083F, KeyframeAnimations.degreeVec(-17.71739F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5417F, KeyframeAnimations.degreeVec(112.28261F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6667F, KeyframeAnimations.degreeVec(116.06889F, 5.11581F, -24.50117F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8333F, KeyframeAnimations.degreeVec(121.56244F, -4.17248F, 19.57737F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0417F, KeyframeAnimations.degreeVec(138.56889F, 5.11581F, -24.50117F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25F, KeyframeAnimations.degreeVec(144.06244F, -4.17248F, 19.57737F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.375F, KeyframeAnimations.degreeVec(147.28261F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.625F, KeyframeAnimations.degreeVec(147.28261F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.875F, KeyframeAnimations.degreeVec(134.36221F, 8.81113F, -8.90172F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.0417F, KeyframeAnimations.degreeVec(132.05966F, -8.35927F, 9.70506F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.25F, KeyframeAnimations.degreeVec(134.36221F, 8.81113F, -8.90172F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.5F, KeyframeAnimations.degreeVec(147.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.degreeVec(97.5F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("head",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6766666F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083433F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.75F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.375F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.7083435F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.875F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.posVec(0F, 0F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.3433335F, KeyframeAnimations.posVec(0F, 1F, -4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5416765F, KeyframeAnimations.posVec(0F, 1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8343335F, KeyframeAnimations.posVec(0F, 1F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.041677F, KeyframeAnimations.posVec(0F, 1F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.posVec(0F, 1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("head",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6667F, KeyframeAnimations.degreeVec(13.086194851950495F, 17.072279894057374F, 3.9039914156746818F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2083F, KeyframeAnimations.degreeVec(14.143781649092034F, -13.465422583043619F, -8.330210660839839F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.75F, KeyframeAnimations.degreeVec(-5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.375F, KeyframeAnimations.degreeVec(-22.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.degreeVec(67.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.7083435F, KeyframeAnimations.degreeVec(12.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.875F, KeyframeAnimations.degreeVec(11.600989497644605F, 15.69916503242257F, -1.7431514355125728F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.degreeVec(-15.899010502355395F, -15.69916503242257F, 1.7431514355125728F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.3433335F, KeyframeAnimations.degreeVec(-43.399010502355395F, 15.69916503242257F, -1.7431514355125728F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5416765F, KeyframeAnimations.degreeVec(-60F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8343335F, KeyframeAnimations.degreeVec(-60F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.041677F, KeyframeAnimations.degreeVec(-58.91612381394225F, -9.995427666612159F, 28.83329384672652F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.25F, KeyframeAnimations.degreeVec(-58.91612381394225F, 9.995427666612159F, -28.83329384672652F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.degreeVec(-50F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("right_arm",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.posVec(2.22F, 0F, 0.86F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.posVec(3.12F, 0F, 4.29F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1676667F, KeyframeAnimations.posVec(2.97F, 0F, 4.44F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2916767F, KeyframeAnimations.posVec(2.81F, 9F, 4.41F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.3433333F, KeyframeAnimations.posVec(2.76F, 8.95F, 8.4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4583433F, KeyframeAnimations.posVec(3.12F, 0F, 4.29F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.625F, KeyframeAnimations.posVec(2.79F, 4.4F, 7.96F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.75F, KeyframeAnimations.posVec(3.12F, 0F, 4.29F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2083F, KeyframeAnimations.posVec(1F, 0F, 4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.posVec(-1F, 0F, 4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9167665F, KeyframeAnimations.posVec(0F, -5F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.posVec(1F, 0F, 4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2916765F, KeyframeAnimations.posVec(1F, -5F, 2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.posVec(1F, -5F, 2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75F, KeyframeAnimations.posVec(1F, -10F, 2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.041677F, KeyframeAnimations.posVec(1F, -6F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.208343F, KeyframeAnimations.posVec(5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.375F, KeyframeAnimations.posVec(1F, -6F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.posVec(5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.posVec(0F, -5F, 2F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("right_arm",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.degreeVec(-101.8036F, -21.29587F, 30.61478F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.degreeVec(-101.8036F, -21.29587F, 30.61478F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(48.7585F, -17.61941F, 9.9865F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1667F, KeyframeAnimations.degreeVec(48.7585F, -17.61941F, 9.9865F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4583F, KeyframeAnimations.degreeVec(-116.44114910879516F, 19.3433334118835F, 10.863704906542015F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.75F, KeyframeAnimations.degreeVec(-89.04994F, -4.19657F, -1.47845F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2083F, KeyframeAnimations.degreeVec(-158.30728F, 3.7152F, -1.52352F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.degreeVec(-87.07754F, -0.02625F, 3.132F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.9167665F, KeyframeAnimations.degreeVec(-156.29763744742513F, -35.82603738046282F, -5.757830407450911F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0834335F, KeyframeAnimations.degreeVec(-90F, 17.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.2916765F, KeyframeAnimations.degreeVec(-168.20592954115864F, -20.448262127520593F, 14.45370892182791F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.degreeVec(-89.99999913388092F, 10.00000003724108F, -17.499999849600044F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.75F, KeyframeAnimations.degreeVec(-182.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.041677F, KeyframeAnimations.degreeVec(-185F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.208343F, KeyframeAnimations.degreeVec(-179.99999999999955F, 20F, -89.99999999999955F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.375F, KeyframeAnimations.degreeVec(-185F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.degreeVec(-179.99999999999955F, 20F, -89.99999999999955F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.degreeVec(-185F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("left_arm",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.posVec(-0.28F, 5F, 10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.posVec(-1.51F, 4.35F, 4.33F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167F, KeyframeAnimations.posVec(-0.6F, 3.61F, 4.63F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1667F, KeyframeAnimations.posVec(-0.6F, 3.61F, 0.63F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6667F, KeyframeAnimations.posVec(-2.85F, -0.1F, 3.33F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2083F, KeyframeAnimations.posVec(-1F, 0F, 4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5416765F, KeyframeAnimations.posVec(-1F, 0F, 4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6766665F, KeyframeAnimations.posVec(0F, -5F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335F, KeyframeAnimations.posVec(-1F, 0F, 4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0416765F, KeyframeAnimations.posVec(-1F, -5F, 2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25F, KeyframeAnimations.posVec(-1F, -5F, 2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.posVec(-1F, -10F, 2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8343335F, KeyframeAnimations.posVec(-1F, -2F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.041677F, KeyframeAnimations.posVec(-1F, -6F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.208343F, KeyframeAnimations.posVec(-5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.375F, KeyframeAnimations.posVec(-1F, -6F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.posVec(-5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.posVec(0F, -5F, 2F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("left_arm",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2917F, KeyframeAnimations.degreeVec(-63.89288F, -0.52011F, 2.09491F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.degreeVec(-63.89288F, -0.52011F, 2.09491F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.degreeVec(-62.87857F, 15.15061F, 9.97445F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.9167F, KeyframeAnimations.degreeVec(-86.93642F, 17.45026F, 4.05284F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.1667F, KeyframeAnimations.degreeVec(-86.93642F, 17.45026F, 4.05284F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4583F, KeyframeAnimations.degreeVec(-86.93642F, 17.45026F, 4.05284F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6667F, KeyframeAnimations.degreeVec(63.0984F, 8.83573F, -8.71284F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8333F, KeyframeAnimations.degreeVec(35.5984F, 8.83573F, -8.71284F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2083F, KeyframeAnimations.degreeVec(-153.27474F, -0.02953F, 3.5235F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.5417F, KeyframeAnimations.degreeVec(-87.07754F, -0.02625F, 3.132F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6766665F, KeyframeAnimations.degreeVec(-156.29763744742513F, 35.82603738046282F, 5.757830407450911F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8343335F, KeyframeAnimations.degreeVec(-90F, -17.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.0416765F, KeyframeAnimations.degreeVec(-168.20592954115864F, 20.448262127520593F, -14.45370892182791F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.25F, KeyframeAnimations.degreeVec(-89.99999913388092F, -10.00000003724108F, 17.499999849600044F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5F, KeyframeAnimations.degreeVec(-182.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8343335F, KeyframeAnimations.degreeVec(-77.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.041677F, KeyframeAnimations.degreeVec(-185F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.208343F, KeyframeAnimations.degreeVec(-179.99999999999955F, -20F, 89.99999999999955F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.375F, KeyframeAnimations.degreeVec(-185F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.541677F, KeyframeAnimations.degreeVec(-179.99999999999955F, -20F, 89.99999999999955F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.degreeVec(-185F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.posVec(0F, -13.98F, -2.37F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.posVec(0F, -13.98F, -2.37F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.3333F, KeyframeAnimations.posVec(0F, -13.98F, -2.37F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5833F, KeyframeAnimations.posVec(0F, -7F, -3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8333F, KeyframeAnimations.posVec(0F, -9F, -3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.0833F, KeyframeAnimations.posVec(0F, -16.71F, -3.69F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.291677F, KeyframeAnimations.posVec(0F, -19F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.5F, KeyframeAnimations.posVec(0F, -28F, -5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.posVec(0F, -42F, -11F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.degreeVec(113.27F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.degreeVec(113.27F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.3333F, KeyframeAnimations.degreeVec(113.27F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5833F, KeyframeAnimations.degreeVec(182.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8333F, KeyframeAnimations.degreeVec(120F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.0833F, KeyframeAnimations.degreeVec(182.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.2917F, KeyframeAnimations.degreeVec(120F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.5F, KeyframeAnimations.degreeVec(157.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.708343F, KeyframeAnimations.degreeVec(102.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.degreeVec(125F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.posVec(0F, -14.01F, -2.35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.posVec(0F, -14.01F, -2.35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.3333F, KeyframeAnimations.posVec(0F, -14.01F, -2.35F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5833F, KeyframeAnimations.posVec(0F, -5F, -4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8333F, KeyframeAnimations.posVec(0F, -7F, -4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.0833F, KeyframeAnimations.posVec(0F, -15.5F, -3.76F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.2917F, KeyframeAnimations.posVec(0F, -19F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.5F, KeyframeAnimations.posVec(0F, -28F, -5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.676667F, KeyframeAnimations.posVec(0F, -34F, -4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.posVec(0F, -42F, -11F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.5F, KeyframeAnimations.degreeVec(114.98F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.7083F, KeyframeAnimations.degreeVec(114.98F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.3333F, KeyframeAnimations.degreeVec(114.98F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.5833F, KeyframeAnimations.degreeVec(90F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.8333F, KeyframeAnimations.degreeVec(172.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.0833F, KeyframeAnimations.degreeVec(90F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.2917F, KeyframeAnimations.degreeVec(197.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.5F, KeyframeAnimations.degreeVec(90F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.676667F, KeyframeAnimations.degreeVec(197.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.958343F, KeyframeAnimations.degreeVec(90F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.build();

	public static final AnimationDefinition WARDEN_EMERGE = AnimationDefinition.Builder.withLength(7.24F)
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -63F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.posVec(0F, -56F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.16F, KeyframeAnimations.posVec(0F, -27F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.posVec(0F, -14F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.92F, KeyframeAnimations.posVec(0F, -11F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.08F, KeyframeAnimations.posVec(0F, -14F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.44F, KeyframeAnimations.posVec(0F, -6F, -3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.56F, KeyframeAnimations.posVec(0F, -4F, -3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.68F, KeyframeAnimations.posVec(0F, -6F, -3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.04F, KeyframeAnimations.posVec(0F, -3F, -4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.24F, KeyframeAnimations.posVec(0F, -3F, -4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.44F, KeyframeAnimations.posVec(0F, -3.19F, -5.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.64F, KeyframeAnimations.posVec(0F, -3F, -4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.68F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(7.16F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("body",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.degreeVec(0F, 0F, -22.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.degreeVec(0F, 0F, -7.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.degreeVec(0F, 0F, 10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8F, KeyframeAnimations.degreeVec(0F, 0F, 10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(0F, 0F, 10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.degreeVec(0F, 0F, 10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.degreeVec(25F, 0F, -7.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.92F, KeyframeAnimations.degreeVec(35F, 0F, -7.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.08F, KeyframeAnimations.degreeVec(25F, 0F, -7.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.44F, KeyframeAnimations.degreeVec(47.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.56F, KeyframeAnimations.degreeVec(47.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.68F, KeyframeAnimations.degreeVec(47.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.04F, KeyframeAnimations.degreeVec(70F, 0F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.24F, KeyframeAnimations.degreeVec(70F, 0F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.44F, KeyframeAnimations.degreeVec(79.38F, 0F, 2.66F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.64F, KeyframeAnimations.degreeVec(70F, 0F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.68F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(7.16F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("head",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.92F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.posVec(0F, 0.47F, -0.95F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.32F, KeyframeAnimations.posVec(0F, 0.47F, -0.95F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4F, KeyframeAnimations.posVec(0F, 0.47F, -0.95F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.posVec(0F, 1F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.76F, KeyframeAnimations.posVec(0F, 1F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.84F, KeyframeAnimations.posVec(0F, 1F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.92F, KeyframeAnimations.posVec(0F, 1F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.64F, KeyframeAnimations.posVec(0F, -2F, -2F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.posVec(0F, -4F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.04F, KeyframeAnimations.posVec(0F, -1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.12F, KeyframeAnimations.posVec(0F, -1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.24F, KeyframeAnimations.posVec(0F, -1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.44F, KeyframeAnimations.posVec(0F, -1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.52F, KeyframeAnimations.posVec(0F, -1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.64F, KeyframeAnimations.posVec(0F, -1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5F, KeyframeAnimations.posVec(0F, -1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.4F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.08F, KeyframeAnimations.posVec(0F, -1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(7.08F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("head",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.degreeVec(70F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.92F, KeyframeAnimations.degreeVec(0.74F, 0F, -40.38F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.16F, KeyframeAnimations.degreeVec(-67.5F, 0F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.degreeVec(-67.5F, 0F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.32F, KeyframeAnimations.degreeVec(-47.5F, 0F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4F, KeyframeAnimations.degreeVec(-67.5F, 0F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.degreeVec(-67.5F, 0F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.76F, KeyframeAnimations.degreeVec(-67.5F, 0F, -5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.84F, KeyframeAnimations.degreeVec(-52.5F, 0F, -5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.92F, KeyframeAnimations.degreeVec(-67.5F, 0F, -5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.64F, KeyframeAnimations.degreeVec(-17.5F, 0F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.degreeVec(70F, 0F, 12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.04F, KeyframeAnimations.degreeVec(70F, 0F, 12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.12F, KeyframeAnimations.degreeVec(80F, 0F, 12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.24F, KeyframeAnimations.degreeVec(70F, 0F, 12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.44F, KeyframeAnimations.degreeVec(70F, 0F, 12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.52F, KeyframeAnimations.degreeVec(80F, 0F, 12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.64F, KeyframeAnimations.degreeVec(70F, 0F, 12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5F, KeyframeAnimations.degreeVec(77.5F, 0F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.4F, KeyframeAnimations.degreeVec(42.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.08F, KeyframeAnimations.degreeVec(77.5F, 0F, -2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(7.08F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("right_arm",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.posVec(3F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -21F, 9F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.posVec(2F, -2F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8F, KeyframeAnimations.posVec(2F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.posVec(2F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.posVec(2F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.08F, KeyframeAnimations.posVec(2F, -2F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.24F, KeyframeAnimations.posVec(2F, 2.71F, 3.86F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.36F, KeyframeAnimations.posVec(2F, 1F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.posVec(2F, 3F, 3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.08F, KeyframeAnimations.posVec(2F, 3F, 3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.44F, KeyframeAnimations.posVec(2.67F, 4F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.56F, KeyframeAnimations.posVec(2.67F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.68F, KeyframeAnimations.posVec(0F, 4F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.84F, KeyframeAnimations.posVec(0F, 2F, 2.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.04F, KeyframeAnimations.posVec(2F, 0.5F, 4F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.16F, KeyframeAnimations.posVec(2F, 0F, 4.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.56F, KeyframeAnimations.posVec(2F, -1.5F, 6F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6F, KeyframeAnimations.posVec(1.64F, -1.07F, 5.05F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.48F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("right_arm",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.degreeVec(17.5F, 0F, 22.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.degreeVec(0F, 0F, 20F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.degreeVec(-152.5F, 2.5F, 7.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.degreeVec(-180F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8F, KeyframeAnimations.degreeVec(-97.5F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.92F, KeyframeAnimations.degreeVec(-93.62F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.04F, KeyframeAnimations.degreeVec(-90F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(-90F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.56F, KeyframeAnimations.degreeVec(-88.97583863063569F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.72F, KeyframeAnimations.degreeVec(-88.97583863063569F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.degreeVec(-90F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.08F, KeyframeAnimations.degreeVec(-95F, 12.5F, -10F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.24F, KeyframeAnimations.degreeVec(-83.93F, 3.93F, 5.71F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.36F, KeyframeAnimations.degreeVec(-80F, 7.5F, 17.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.degreeVec(-67.5F, 2.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.08F, KeyframeAnimations.degreeVec(-67.5F, 2.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.44F, KeyframeAnimations.degreeVec(-55F, 2.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.56F, KeyframeAnimations.degreeVec(-60F, 2.5F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.68F, KeyframeAnimations.degreeVec(-52.5F, 0F, -5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.84F, KeyframeAnimations.degreeVec(-62.18749999999994F, 1.1225000000000547F, -5.125625000000018F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.04F, KeyframeAnimations.degreeVec(-72.18749999999994F, 1.1225000000000547F, -5.125625000000018F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.16F, KeyframeAnimations.degreeVec(-69.68749999999994F, 1.1225000000000547F, -5.125625000000018F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.6F, KeyframeAnimations.degreeVec(-75.88972091351246F, 2.030500222713836F, -5.12171674263107F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.92F, KeyframeAnimations.degreeVec(-79.93836177589901F, -7.770407293518893F, -5.163902270852068F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.44F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.96F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_arm",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.12F, KeyframeAnimations.posVec(0F, -8F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6F, KeyframeAnimations.posVec(0F, -8F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.88F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.posVec(-2F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.posVec(-4F, 3F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8F, KeyframeAnimations.posVec(-4F, 3F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.posVec(-4F, 3F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.posVec(-4F, 3F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.04F, KeyframeAnimations.posVec(-3.23F, 5.7F, 4.97F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.16F, KeyframeAnimations.posVec(-1.49F, 2.22F, 5.25F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.posVec(-1.14F, 1.71F, 1.86F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.92F, KeyframeAnimations.posVec(-1.14F, 1.21F, 3.86F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.08F, KeyframeAnimations.posVec(-1.14F, 2.71F, 4.86F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.44F, KeyframeAnimations.posVec(-1F, 1F, 3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.56F, KeyframeAnimations.posVec(0F, 1F, 1F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.68F, KeyframeAnimations.posVec(0F, 1F, 3F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.84F, KeyframeAnimations.posVec(-0.54F, 4.05F, 1.9699999999999998F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.08F, KeyframeAnimations.posVec(-2F, 1F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.24F, KeyframeAnimations.posVec(-2.12F, 0.6399999999999999F, 5.26F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.56F, KeyframeAnimations.posVec(-2.19F, 0.8899999999999999F, 6.45F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.92F, KeyframeAnimations.posVec(-2F, 3F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.44F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_arm",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.12F, KeyframeAnimations.degreeVec(-167.5F, -17.5F, -7.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.6F, KeyframeAnimations.degreeVec(-167.5F, -17.5F, -7.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.88F, KeyframeAnimations.degreeVec(-175F, -17.5F, 15F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.16F, KeyframeAnimations.degreeVec(-190F, -17.5F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.28F, KeyframeAnimations.degreeVec(-95F, -5F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.4F, KeyframeAnimations.degreeVec(-91.72749999999995F, -7.306250000000145F, 0.48499999999989085F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.52F, KeyframeAnimations.degreeVec(-88.28838192419839F, -11.658053935860298F, -5.168775510204268F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.degreeVec(-90F, -17.5F, -12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8F, KeyframeAnimations.degreeVec(-90F, -17.5F, -12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(-90F, -17.5F, -12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.degreeVec(-90F, -17.5F, -12.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.04F, KeyframeAnimations.degreeVec(-81.29F, -10.64F, -14.21F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.16F, KeyframeAnimations.degreeVec(-83.5F, -5.5F, -15.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.degreeVec(-62.5F, -7.5F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.92F, KeyframeAnimations.degreeVec(-58.75F, -3.75F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.08F, KeyframeAnimations.degreeVec(-55F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.44F, KeyframeAnimations.degreeVec(-52.5F, 0F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.56F, KeyframeAnimations.degreeVec(-50F, 0F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.68F, KeyframeAnimations.degreeVec(-52.5F, 0F, 5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.84F, KeyframeAnimations.degreeVec(-47.18749999999994F, -1.1225000000000547F, 5.125625000000018F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.04F, KeyframeAnimations.degreeVec(-62.18749999999994F, -1.1225000000000547F, 5.125625000000018F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.24F, KeyframeAnimations.degreeVec(-67.51F, -1.15F, 5.27F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.56F, KeyframeAnimations.degreeVec(-71.54F, -1.2F, 5.51F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.84F, KeyframeAnimations.degreeVec(-62.18749999999994F, -1.1225000000000547F, 5.125625000000018F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.36F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(7.08F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("right_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -63F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.posVec(0F, -56F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.36F, KeyframeAnimations.posVec(0F, -22F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.76F, KeyframeAnimations.posVec(0F, -12.28F, 2.48F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.92F, KeyframeAnimations.posVec(0F, -9.28F, 2.48F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.08F, KeyframeAnimations.posVec(0F, -12.28F, 2.48F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.32F, KeyframeAnimations.posVec(0F, -4.14F, 4.14F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.48F, KeyframeAnimations.posVec(0F, -0.57F, -8.43F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.6F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.8F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.64F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("right_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.24F, KeyframeAnimations.degreeVec(15F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.degreeVec(-35F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.84F, KeyframeAnimations.degreeVec(35F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3F, KeyframeAnimations.degreeVec(-5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.12F, KeyframeAnimations.degreeVec(35F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.24F, KeyframeAnimations.degreeVec(-30F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.44F, KeyframeAnimations.degreeVec(35F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.56F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.32F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.48F, KeyframeAnimations.degreeVec(55F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.6F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.8F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.64F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_leg",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, -63F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.posVec(0F, -56F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.8F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.posVec(0F, -32F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.36F, KeyframeAnimations.posVec(0F, -22F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.84F, KeyframeAnimations.posVec(-4F, 2F, -7F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4F, KeyframeAnimations.posVec(-4F, 0F, -5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.36F, KeyframeAnimations.posVec(-4.13F, -0.25F, -7.39F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.52F, KeyframeAnimations.posVec(-4.2F, -0.27F, -6.6899999999999995F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.68F, KeyframeAnimations.posVec(-4F, 0F, -9F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.84F, KeyframeAnimations.posVec(-2F, 2F, -3.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.8F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.64F, KeyframeAnimations.posVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation("left_leg",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.24F, KeyframeAnimations.degreeVec(-15F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.degreeVec(35F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.84F, KeyframeAnimations.degreeVec(-35F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3F, KeyframeAnimations.degreeVec(27.5F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.12F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.24F, KeyframeAnimations.degreeVec(60F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.36F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.84F, KeyframeAnimations.degreeVec(20F, 0F, -17.5F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.36F, KeyframeAnimations.degreeVec(10.22F, 0F, 1.03F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.52F, KeyframeAnimations.degreeVec(11.370000000000001F, 0F, 0.58F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.68F, KeyframeAnimations.degreeVec(20F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(4.84F, KeyframeAnimations.degreeVec(10F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(5.8F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(6.64F, KeyframeAnimations.degreeVec(0F, 0F, 0F),
					AnimationChannel.Interpolations.CATMULLROM)))
		.build();
	public static final AnimationDefinition DYING = Builder.withLength(3.5F)
		.addAnimation(
			"bone",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.56F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2.44F, KeyframeAnimations.degreeVec(-37.7838F, -14.24F, -17.6045F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"bone",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.36F, KeyframeAnimations.posVec(0.0F, -100F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.92F, KeyframeAnimations.posVec(0.0F, -190F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.48F, KeyframeAnimations.posVec(0.0F, -500F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"body",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.56F, KeyframeAnimations.degreeVec(-12.59F, 0F, 6.67F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.degreeVec(-42.5F, 0.0F, 22.5F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"body",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.posVec(5.7F, 0F, 4F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.44F, KeyframeAnimations.posVec(12.0F, 0F, 11F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.44F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"head",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.degreeVec(9.5459F, 2.9932F, -17.25F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.32F, KeyframeAnimations.degreeVec(-17.5093F, -0.434F, 2.4621F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.88F, KeyframeAnimations.degreeVec(37.3656F, -0.1965F, -5.1569F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(37.3656F, -0.1965F, -5.1569F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"head",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_arm",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.48F, KeyframeAnimations.degreeVec(-52.5F, -0F, 50F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(-59.5544F, 33.4855F, 67.9672F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.degreeVec(-73.7812F, -48.0134F, 72.9396F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.12F, KeyframeAnimations.degreeVec(-72.5422F, 17.6713F, -9.7739F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_arm",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.48F, KeyframeAnimations.posVec(1F, 0.0F, 2F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.12F, KeyframeAnimations.posVec(2F, -1F, 1F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.posVec(2.66F, -0.22F, 0.34F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.12F, KeyframeAnimations.posVec(2F, -1F, 3F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_arm",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2F, KeyframeAnimations.degreeVec(0, 0, -12.5F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.56F, KeyframeAnimations.degreeVec(-17.1773F, -40.7763F, -47.1799F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.0F, KeyframeAnimations.degreeVec(-24.0177F, 6.4316F, -116.2232F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.68F, KeyframeAnimations.degreeVec(-79.9936F, -13.4086F, -27.2842F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.08F, KeyframeAnimations.degreeVec(-80.2279F, -3.0828F, -21.3852F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_arm",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.88F, KeyframeAnimations.posVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_leg",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16F, KeyframeAnimations.degreeVec(-20.2134F, 4.3897F, 7.6436F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.degreeVec(-48.42F, 5.21F, -0.33F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.88F, KeyframeAnimations.degreeVec(-133.8547F, 12.8091F, -12.025F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_leg",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.posVec(4.78F, 6F, 0.42F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.84F, KeyframeAnimations.posVec(8.0F, 6F, 2F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.44F, KeyframeAnimations.posVec(12F, 8F, 5F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.16F, KeyframeAnimations.degreeVec(1F, 6F, -1F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_leg",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.degreeVec(-12.4952F, -9.8466F, -5.9812F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.88F, KeyframeAnimations.degreeVec(-77.4825F, -0.8548F, 20.1506F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.52F, KeyframeAnimations.degreeVec(-107.48F, -0.85F, 20.15F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_leg",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.08F, KeyframeAnimations.posVec(10F, 0F, 6F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.44F, KeyframeAnimations.posVec(0F, 3F, -6F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.build();
	public static final AnimationDefinition WATER_DYING = Builder.withLength(3.5F)
		.addAnimation(
			"bone",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.36F, KeyframeAnimations.degreeVec(-47.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.4F, KeyframeAnimations.degreeVec(-47.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"bone",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16F, KeyframeAnimations.posVec(0.0F, 0.0F, 6.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.08F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.72F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"body",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.12F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.44F, KeyframeAnimations.degreeVec(-15F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.48F, KeyframeAnimations.degreeVec(-27.4615F, -4.7235F, 10.7F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"body",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.44F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.48F, KeyframeAnimations.posVec(1F, -1F, 1F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"head",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.04F, KeyframeAnimations.degreeVec(-32.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.24F, KeyframeAnimations.degreeVec(27.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.68F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.6F, KeyframeAnimations.degreeVec(-30.0214F, 0.3262F, -7.4929F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.84F, KeyframeAnimations.degreeVec(-37.5379F, -0.434F, 9.9907F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.28F, KeyframeAnimations.degreeVec(-37.5379F, -0.434F, 9.9907F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_arm",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.28F, KeyframeAnimations.degreeVec(-90.6636F, 9.917F, -1.8476F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.84F, KeyframeAnimations.degreeVec(-4.1947F, 21.3089F, 6.3256F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.44F, KeyframeAnimations.degreeVec(42.5707F, -3.6382F, 15.171F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(49.4331F, -3.0042F, 15.7028F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.28F, KeyframeAnimations.degreeVec(79.4684F, 3.3016F, 9.7983F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_arm",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.posVec(1F, 0F, -4F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.28F, KeyframeAnimations.posVec(0F, -3F, -4F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_arm",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.24F, KeyframeAnimations.degreeVec(-55.6563F, -5.082F, -1.6751F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.degreeVec(47.9174F, 14.298F, -25.7058F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(47.9174F, 14.298F, -25.7058F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.28F, KeyframeAnimations.degreeVec(76.9331F, 3.0042F, -15.7028F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_arm",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.posVec(-2F, 0F, -4F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_leg",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2F, KeyframeAnimations.degreeVec(-80.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.72F, KeyframeAnimations.degreeVec(-42.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.degreeVec(35F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.72F, KeyframeAnimations.degreeVec(35F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.44F, KeyframeAnimations.degreeVec(42.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.96F, KeyframeAnimations.degreeVec(35F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_leg",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.08F, KeyframeAnimations.degreeVec(-80.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.degreeVec(-42.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.84F, KeyframeAnimations.degreeVec(35F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.36F, KeyframeAnimations.degreeVec(35F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.4F, KeyframeAnimations.degreeVec(42.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.92F, KeyframeAnimations.degreeVec(35F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.build();
	public static final AnimationDefinition KIRBY_DEATH = Builder.withLength(3.5F)
		.addAnimation(
			"bone",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16F, KeyframeAnimations.posVec(0F, -1F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.28F, KeyframeAnimations.posVec(0F, 32F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.68F, KeyframeAnimations.posVec(0F, 29F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.92F, KeyframeAnimations.posVec(0F, -12F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.04F, KeyframeAnimations.posVec(0F, -12F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -12F, 0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.32F, KeyframeAnimations.posVec(0F, -12F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.08F, KeyframeAnimations.posVec(0F, 50F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.96F, KeyframeAnimations.posVec(0F, -500F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.28F, KeyframeAnimations.posVec(0F, -500F, 0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"bone",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.32F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(3.48F, KeyframeAnimations.degreeVec(0F, 0F, -2465F), AnimationChannel.Interpolations.LINEAR)
			)
		)
		.addAnimation(
			"body",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0.0F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.32F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.48F, KeyframeAnimations.posVec(0F, -21F, 0F), AnimationChannel.Interpolations.LINEAR)
			)
		)
		.addAnimation(
			"body",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16F, KeyframeAnimations.degreeVec(35F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.32F, KeyframeAnimations.degreeVec(-7.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.92F, KeyframeAnimations.degreeVec(2.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(-32.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.12F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"head",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2F, KeyframeAnimations.degreeVec(47.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.32F, KeyframeAnimations.degreeVec(-15F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.92F, KeyframeAnimations.degreeVec(-5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(15F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.04F, KeyframeAnimations.degreeVec(-25F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.degreeVec(35F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.32F, KeyframeAnimations.degreeVec(35F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.52F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_arm",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.posVec(2F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.76F, KeyframeAnimations.posVec(3F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.posVec(3F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_arm",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.24F, KeyframeAnimations.degreeVec(-35.6253F, -25.29298F, -11.45438F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.degreeVec(4.33362F, 22.13475F, 109.16203F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4F, KeyframeAnimations.degreeVec(-19.18171F, 12.05536F, 38.76962F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.44F, KeyframeAnimations.degreeVec(10.48032F, 10.94952F, 120.74846F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.48F, KeyframeAnimations.degreeVec(-11.56478F, 9.79544F, 26.24686F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.56F, KeyframeAnimations.degreeVec(10.9453F, 10.48472F, 123.2485F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.68F, KeyframeAnimations.degreeVec(-8.64542F, 12.44278F, 41.29697F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.76F, KeyframeAnimations.degreeVec(4.18854F, 14.5334F, 92.77552F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(-5.09172F, 14.2477F, 56.60443F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(-0.47662F, 15.10509F, 74.678F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.04F, KeyframeAnimations.degreeVec(-14.59871F, 12.24024F, 67.32805F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.12F, KeyframeAnimations.degreeVec(-28.94953F, 12.06189F, 63.50492F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.degreeVec(-14.6F, 12.24F, 67.33F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_arm",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.posVec(-2F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.76F, KeyframeAnimations.posVec(-3F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.posVec(-3F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_arm",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.24F, KeyframeAnimations.degreeVec(-35.6253F, 25.29298F, 11.45438F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.degreeVec(4.33362F, -22.13475F, -109.16203F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4F, KeyframeAnimations.degreeVec(-19.18171F, -12.05536F, -38.76962F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.44F, KeyframeAnimations.degreeVec(10.48032F, -10.94952F, -120.74846F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.48F, KeyframeAnimations.degreeVec(-11.56478F, -9.79544F, -26.24686F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.56F, KeyframeAnimations.degreeVec(10.9453F, -10.48472F, -123.2485F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.68F, KeyframeAnimations.degreeVec(-8.64542F, -12.44278F, -41.29697F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.76F, KeyframeAnimations.degreeVec(4.18854F, -14.5334F, -92.77552F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(-5.09172F, -14.2477F, -56.60443F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(-0.47662F, -15.10509F, -74.678F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.04F, KeyframeAnimations.degreeVec(15.20535F, -12.39428F, -63.49328F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.12F, KeyframeAnimations.degreeVec(-28.94953F, -12.06189F, -63.50492F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.degreeVec(-14.6F, -12.24F, -67.33F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_leg",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.88F, KeyframeAnimations.posVec(-2F, 13F, -3F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.posVec(-2F, 8F, -8F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.posVec(-2F, 2F, -5F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.2F, KeyframeAnimations.posVec(-2F, 2F, -5F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.32F, KeyframeAnimations.posVec(-2F, 2F, -5F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.48F, KeyframeAnimations.posVec(-2F, -18F, -3F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"right_leg",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16F, KeyframeAnimations.degreeVec(12.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.24F, KeyframeAnimations.degreeVec(-22.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.28F, KeyframeAnimations.degreeVec(12.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.32F, KeyframeAnimations.degreeVec(-37.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.degreeVec(42.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4F, KeyframeAnimations.degreeVec(-27.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.44F, KeyframeAnimations.degreeVec(17.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.48F, KeyframeAnimations.degreeVec(-52.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.degreeVec(32.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.64F, KeyframeAnimations.degreeVec(-20F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.68F, KeyframeAnimations.degreeVec(20F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.76F, KeyframeAnimations.degreeVec(2.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.84F, KeyframeAnimations.degreeVec(2.44081F, -0.54094F, 12.48848F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.04F, KeyframeAnimations.degreeVec(-92.48338F, 2.99703F, 16.02295F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.degreeVec(-92.48F, 3F, 16.02F), AnimationChannel.Interpolations.LINEAR)
			)
		)
		.addAnimation(
			"left_leg",
			new AnimationChannel(
				AnimationChannel.Targets.POSITION,
				new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.8F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.posVec(0F, 10F, -3F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.04F, KeyframeAnimations.posVec(0F, 8F, -10F), AnimationChannel.Interpolations.LINEAR),
				new Keyframe(1.08F, KeyframeAnimations.posVec(0F, 2F, -6F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.28F, KeyframeAnimations.posVec(0F, 2F, -6F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.36F, KeyframeAnimations.posVec(0F, 2F, -6F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.48F, KeyframeAnimations.posVec(0F, -18F, -3F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.addAnimation(
			"left_leg",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.12F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.16F, KeyframeAnimations.degreeVec(10F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.2F, KeyframeAnimations.degreeVec(-5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.24F, KeyframeAnimations.degreeVec(45F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.28F, KeyframeAnimations.degreeVec(-35F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.32F, KeyframeAnimations.degreeVec(35F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.36F, KeyframeAnimations.degreeVec(-37.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.4F, KeyframeAnimations.degreeVec(25F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.44F, KeyframeAnimations.degreeVec(-40F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.48F, KeyframeAnimations.degreeVec(52.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.52F, KeyframeAnimations.degreeVec(-40F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.64F, KeyframeAnimations.degreeVec(37.5F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.76F, KeyframeAnimations.degreeVec(-15F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.84F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1F, KeyframeAnimations.degreeVec(-33.43738F, -19.53723F, -9.46391F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.08F, KeyframeAnimations.degreeVec(-88.43738F, -19.53723F, -9.46391F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.12F, KeyframeAnimations.degreeVec(-100.93738F, -19.53723F, -9.46391F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.32F, KeyframeAnimations.degreeVec(-100.94F, -19.54F, -9.46F), AnimationChannel.Interpolations.CATMULLROM)
			)
		)
		.build();
	public static AnimationDefinition WARDEN_SNIFF = AnimationDefinition.Builder.withLength(4.16F)
		.addAnimation(
			"body",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.56F, KeyframeAnimations.degreeVec(17.5F, 32.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(0.0F, 32.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.8F, KeyframeAnimations.degreeVec(10.0F, -30.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM))
		)
		.addAnimation(
			"head",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, 40.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(-22.5F, 40.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.24F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.52F, KeyframeAnimations.degreeVec(-35.0F, 20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(1.76F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.28F, KeyframeAnimations.degreeVec(0.0F, -20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.6F, KeyframeAnimations.degreeVec(WWEntityConfig.get().warden.wardenBedrockSniff ? -25.0F : 0.0F, -23.6504F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.88F, KeyframeAnimations.degreeVec(0.0F, -20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation(
			"right_arm",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.76F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)))
		.addAnimation(
			"left_arm",
			new AnimationChannel(
				AnimationChannel.Targets.ROTATION,
				new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(0.96F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(2.76F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
				new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)))
		.build();
}
